import fs from "node:fs/promises";
import path from "node:path";
import { generateKeyPairSync } from "node:crypto";

function parseArg(name: string): string | null {
  const idx = process.argv.findIndex((arg) => arg === name);
  if (idx === -1 || idx + 1 >= process.argv.length) return null;
  return process.argv[idx + 1];
}

function hasFlag(name: string): boolean {
  return process.argv.includes(name);
}

function normalizeBits(input: string | null): number {
  const parsed = Number(input || "3072");
  if (!Number.isFinite(parsed) || parsed < 2048) {
    throw new Error("Invalid --bits. Use a number >= 2048 (recommended: 3072 or 4096).");
  }
  return Math.floor(parsed);
}

function pemToEnvLiteral(pem: string): string {
  const trimmed = pem.trim();
  return `"${trimmed.replace(/\n/g, "\\n")}"`;
}

async function main() {
  const outFileRaw = parseArg("--out");
  const bits = normalizeBits(parseArg("--bits"));
  const withDeepScanAlias = hasFlag("--with-deep-scan-alias");

  const { publicKey, privateKey } = generateKeyPairSync("rsa", {
    modulusLength: bits,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });

  const publicLiteral = pemToEnvLiteral(publicKey);
  const privateLiteral = pemToEnvLiteral(privateKey);

  const lines = [
    "# Generated by: bun run --filter web keys:analyze",
    "# Keep ANALYZE_PAYLOAD_PRIVATE_KEY secret.",
    `ANALYZE_PAYLOAD_PUBLIC_KEY=${publicLiteral}`,
    `ANALYZE_PAYLOAD_PRIVATE_KEY=${privateLiteral}`,
  ];

  if (withDeepScanAlias) {
    lines.push(
      "",
      "# Optional compatibility aliases (same keypair):",
      `DEEP_SCAN_PUBLIC_KEY=${publicLiteral}`,
      `DEEP_SCAN_PRIVATE_KEY=${privateLiteral}`
    );
  }

  const output = `${lines.join("\n")}\n`;
  if (outFileRaw) {
    const outFile = path.resolve(outFileRaw);
    await fs.mkdir(path.dirname(outFile), { recursive: true });
    await fs.writeFile(outFile, output, "utf8");
    console.log(`Wrote keypair env block to: ${outFile}`);
  }

  process.stdout.write(output);
}

main().catch((error) => {
  console.error("Failed to generate analyze keypair:", error);
  process.exitCode = 1;
});
