
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const InviteStatus = {
  pending: 'pending',
  sent: 'sent',
  failed: 'failed',
  accepted: 'accepted',
  canceled: 'canceled',
  expired: 'expired'
} as const

export type InviteStatus = (typeof InviteStatus)[keyof typeof InviteStatus]


export const DeliveryStatus = {
  sent: 'sent',
  failed: 'failed',
  skipped: 'skipped'
} as const

export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus]
