
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EmailScan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EmailScan
 * 
 */
export type EmailScanModel = runtime.Types.Result.DefaultSelection<Prisma.$EmailScanPayload>

export type AggregateEmailScan = {
  _count: EmailScanCountAggregateOutputType | null
  _min: EmailScanMinAggregateOutputType | null
  _max: EmailScanMaxAggregateOutputType | null
}

export type EmailScanMinAggregateOutputType = {
  id: string | null
  userId: string | null
  departmentId: string | null
  emailSubject: string | null
  emailSender: string | null
  detectedAt: Date | null
  isPhishing: boolean | null
  detectedBy: string | null
}

export type EmailScanMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  departmentId: string | null
  emailSubject: string | null
  emailSender: string | null
  detectedAt: Date | null
  isPhishing: boolean | null
  detectedBy: string | null
}

export type EmailScanCountAggregateOutputType = {
  id: number
  userId: number
  departmentId: number
  emailSubject: number
  emailSender: number
  detectedAt: number
  isPhishing: number
  detectedBy: number
  links: number
  _all: number
}


export type EmailScanMinAggregateInputType = {
  id?: true
  userId?: true
  departmentId?: true
  emailSubject?: true
  emailSender?: true
  detectedAt?: true
  isPhishing?: true
  detectedBy?: true
}

export type EmailScanMaxAggregateInputType = {
  id?: true
  userId?: true
  departmentId?: true
  emailSubject?: true
  emailSender?: true
  detectedAt?: true
  isPhishing?: true
  detectedBy?: true
}

export type EmailScanCountAggregateInputType = {
  id?: true
  userId?: true
  departmentId?: true
  emailSubject?: true
  emailSender?: true
  detectedAt?: true
  isPhishing?: true
  detectedBy?: true
  links?: true
  _all?: true
}

export type EmailScanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailScan to aggregate.
   */
  where?: Prisma.EmailScanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailScans to fetch.
   */
  orderBy?: Prisma.EmailScanOrderByWithRelationInput | Prisma.EmailScanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmailScanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailScans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailScans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EmailScans
  **/
  _count?: true | EmailScanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmailScanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmailScanMaxAggregateInputType
}

export type GetEmailScanAggregateType<T extends EmailScanAggregateArgs> = {
      [P in keyof T & keyof AggregateEmailScan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmailScan[P]>
    : Prisma.GetScalarType<T[P], AggregateEmailScan[P]>
}




export type EmailScanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailScanWhereInput
  orderBy?: Prisma.EmailScanOrderByWithAggregationInput | Prisma.EmailScanOrderByWithAggregationInput[]
  by: Prisma.EmailScanScalarFieldEnum[] | Prisma.EmailScanScalarFieldEnum
  having?: Prisma.EmailScanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmailScanCountAggregateInputType | true
  _min?: EmailScanMinAggregateInputType
  _max?: EmailScanMaxAggregateInputType
}

export type EmailScanGroupByOutputType = {
  id: string
  userId: string
  departmentId: string
  emailSubject: string
  emailSender: string
  detectedAt: Date
  isPhishing: boolean
  detectedBy: string
  links: string[]
  _count: EmailScanCountAggregateOutputType | null
  _min: EmailScanMinAggregateOutputType | null
  _max: EmailScanMaxAggregateOutputType | null
}

type GetEmailScanGroupByPayload<T extends EmailScanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmailScanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmailScanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmailScanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmailScanGroupByOutputType[P]>
      }
    >
  >



export type EmailScanWhereInput = {
  AND?: Prisma.EmailScanWhereInput | Prisma.EmailScanWhereInput[]
  OR?: Prisma.EmailScanWhereInput[]
  NOT?: Prisma.EmailScanWhereInput | Prisma.EmailScanWhereInput[]
  id?: Prisma.StringFilter<"EmailScan"> | string
  userId?: Prisma.StringFilter<"EmailScan"> | string
  departmentId?: Prisma.StringFilter<"EmailScan"> | string
  emailSubject?: Prisma.StringFilter<"EmailScan"> | string
  emailSender?: Prisma.StringFilter<"EmailScan"> | string
  detectedAt?: Prisma.DateTimeFilter<"EmailScan"> | Date | string
  isPhishing?: Prisma.BoolFilter<"EmailScan"> | boolean
  detectedBy?: Prisma.StringFilter<"EmailScan"> | string
  links?: Prisma.StringNullableListFilter<"EmailScan">
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  department?: Prisma.XOR<Prisma.DepartmentScalarRelationFilter, Prisma.DepartmentWhereInput>
  actions?: Prisma.UserActionListRelationFilter
}

export type EmailScanOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  departmentId?: Prisma.SortOrder
  emailSubject?: Prisma.SortOrder
  emailSender?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
  isPhishing?: Prisma.SortOrder
  detectedBy?: Prisma.SortOrder
  links?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  department?: Prisma.DepartmentOrderByWithRelationInput
  actions?: Prisma.UserActionOrderByRelationAggregateInput
}

export type EmailScanWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EmailScanWhereInput | Prisma.EmailScanWhereInput[]
  OR?: Prisma.EmailScanWhereInput[]
  NOT?: Prisma.EmailScanWhereInput | Prisma.EmailScanWhereInput[]
  userId?: Prisma.StringFilter<"EmailScan"> | string
  departmentId?: Prisma.StringFilter<"EmailScan"> | string
  emailSubject?: Prisma.StringFilter<"EmailScan"> | string
  emailSender?: Prisma.StringFilter<"EmailScan"> | string
  detectedAt?: Prisma.DateTimeFilter<"EmailScan"> | Date | string
  isPhishing?: Prisma.BoolFilter<"EmailScan"> | boolean
  detectedBy?: Prisma.StringFilter<"EmailScan"> | string
  links?: Prisma.StringNullableListFilter<"EmailScan">
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  department?: Prisma.XOR<Prisma.DepartmentScalarRelationFilter, Prisma.DepartmentWhereInput>
  actions?: Prisma.UserActionListRelationFilter
}, "id">

export type EmailScanOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  departmentId?: Prisma.SortOrder
  emailSubject?: Prisma.SortOrder
  emailSender?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
  isPhishing?: Prisma.SortOrder
  detectedBy?: Prisma.SortOrder
  links?: Prisma.SortOrder
  _count?: Prisma.EmailScanCountOrderByAggregateInput
  _max?: Prisma.EmailScanMaxOrderByAggregateInput
  _min?: Prisma.EmailScanMinOrderByAggregateInput
}

export type EmailScanScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmailScanScalarWhereWithAggregatesInput | Prisma.EmailScanScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmailScanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmailScanScalarWhereWithAggregatesInput | Prisma.EmailScanScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EmailScan"> | string
  userId?: Prisma.StringWithAggregatesFilter<"EmailScan"> | string
  departmentId?: Prisma.StringWithAggregatesFilter<"EmailScan"> | string
  emailSubject?: Prisma.StringWithAggregatesFilter<"EmailScan"> | string
  emailSender?: Prisma.StringWithAggregatesFilter<"EmailScan"> | string
  detectedAt?: Prisma.DateTimeWithAggregatesFilter<"EmailScan"> | Date | string
  isPhishing?: Prisma.BoolWithAggregatesFilter<"EmailScan"> | boolean
  detectedBy?: Prisma.StringWithAggregatesFilter<"EmailScan"> | string
  links?: Prisma.StringNullableListFilter<"EmailScan">
}

export type EmailScanCreateInput = {
  id?: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
  user: Prisma.UserCreateNestedOneWithoutEmailScansInput
  department: Prisma.DepartmentCreateNestedOneWithoutScansInput
  actions?: Prisma.UserActionCreateNestedManyWithoutEmailScanInput
}

export type EmailScanUncheckedCreateInput = {
  id?: string
  userId: string
  departmentId: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
  actions?: Prisma.UserActionUncheckedCreateNestedManyWithoutEmailScanInput
}

export type EmailScanUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
  user?: Prisma.UserUpdateOneRequiredWithoutEmailScansNestedInput
  department?: Prisma.DepartmentUpdateOneRequiredWithoutScansNestedInput
  actions?: Prisma.UserActionUpdateManyWithoutEmailScanNestedInput
}

export type EmailScanUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  departmentId?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
  actions?: Prisma.UserActionUncheckedUpdateManyWithoutEmailScanNestedInput
}

export type EmailScanCreateManyInput = {
  id?: string
  userId: string
  departmentId: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
}

export type EmailScanUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
}

export type EmailScanUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  departmentId?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
}

export type EmailScanListRelationFilter = {
  every?: Prisma.EmailScanWhereInput
  some?: Prisma.EmailScanWhereInput
  none?: Prisma.EmailScanWhereInput
}

export type EmailScanOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmailScanCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  departmentId?: Prisma.SortOrder
  emailSubject?: Prisma.SortOrder
  emailSender?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
  isPhishing?: Prisma.SortOrder
  detectedBy?: Prisma.SortOrder
  links?: Prisma.SortOrder
}

export type EmailScanMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  departmentId?: Prisma.SortOrder
  emailSubject?: Prisma.SortOrder
  emailSender?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
  isPhishing?: Prisma.SortOrder
  detectedBy?: Prisma.SortOrder
}

export type EmailScanMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  departmentId?: Prisma.SortOrder
  emailSubject?: Prisma.SortOrder
  emailSender?: Prisma.SortOrder
  detectedAt?: Prisma.SortOrder
  isPhishing?: Prisma.SortOrder
  detectedBy?: Prisma.SortOrder
}

export type EmailScanScalarRelationFilter = {
  is?: Prisma.EmailScanWhereInput
  isNot?: Prisma.EmailScanWhereInput
}

export type EmailScanCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutUserInput, Prisma.EmailScanUncheckedCreateWithoutUserInput> | Prisma.EmailScanCreateWithoutUserInput[] | Prisma.EmailScanUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutUserInput | Prisma.EmailScanCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EmailScanCreateManyUserInputEnvelope
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
}

export type EmailScanUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutUserInput, Prisma.EmailScanUncheckedCreateWithoutUserInput> | Prisma.EmailScanCreateWithoutUserInput[] | Prisma.EmailScanUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutUserInput | Prisma.EmailScanCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.EmailScanCreateManyUserInputEnvelope
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
}

export type EmailScanUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutUserInput, Prisma.EmailScanUncheckedCreateWithoutUserInput> | Prisma.EmailScanCreateWithoutUserInput[] | Prisma.EmailScanUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutUserInput | Prisma.EmailScanCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EmailScanUpsertWithWhereUniqueWithoutUserInput | Prisma.EmailScanUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EmailScanCreateManyUserInputEnvelope
  set?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  disconnect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  delete?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  update?: Prisma.EmailScanUpdateWithWhereUniqueWithoutUserInput | Prisma.EmailScanUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EmailScanUpdateManyWithWhereWithoutUserInput | Prisma.EmailScanUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EmailScanScalarWhereInput | Prisma.EmailScanScalarWhereInput[]
}

export type EmailScanUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutUserInput, Prisma.EmailScanUncheckedCreateWithoutUserInput> | Prisma.EmailScanCreateWithoutUserInput[] | Prisma.EmailScanUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutUserInput | Prisma.EmailScanCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.EmailScanUpsertWithWhereUniqueWithoutUserInput | Prisma.EmailScanUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.EmailScanCreateManyUserInputEnvelope
  set?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  disconnect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  delete?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  update?: Prisma.EmailScanUpdateWithWhereUniqueWithoutUserInput | Prisma.EmailScanUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.EmailScanUpdateManyWithWhereWithoutUserInput | Prisma.EmailScanUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.EmailScanScalarWhereInput | Prisma.EmailScanScalarWhereInput[]
}

export type EmailScanCreatelinksInput = {
  set: string[]
}

export type EmailScanUpdatelinksInput = {
  set?: string[]
  push?: string | string[]
}

export type EmailScanCreateNestedOneWithoutActionsInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutActionsInput, Prisma.EmailScanUncheckedCreateWithoutActionsInput>
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutActionsInput
  connect?: Prisma.EmailScanWhereUniqueInput
}

export type EmailScanUpdateOneRequiredWithoutActionsNestedInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutActionsInput, Prisma.EmailScanUncheckedCreateWithoutActionsInput>
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutActionsInput
  upsert?: Prisma.EmailScanUpsertWithoutActionsInput
  connect?: Prisma.EmailScanWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.EmailScanUpdateToOneWithWhereWithoutActionsInput, Prisma.EmailScanUpdateWithoutActionsInput>, Prisma.EmailScanUncheckedUpdateWithoutActionsInput>
}

export type EmailScanCreateNestedManyWithoutDepartmentInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutDepartmentInput, Prisma.EmailScanUncheckedCreateWithoutDepartmentInput> | Prisma.EmailScanCreateWithoutDepartmentInput[] | Prisma.EmailScanUncheckedCreateWithoutDepartmentInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutDepartmentInput | Prisma.EmailScanCreateOrConnectWithoutDepartmentInput[]
  createMany?: Prisma.EmailScanCreateManyDepartmentInputEnvelope
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
}

export type EmailScanUncheckedCreateNestedManyWithoutDepartmentInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutDepartmentInput, Prisma.EmailScanUncheckedCreateWithoutDepartmentInput> | Prisma.EmailScanCreateWithoutDepartmentInput[] | Prisma.EmailScanUncheckedCreateWithoutDepartmentInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutDepartmentInput | Prisma.EmailScanCreateOrConnectWithoutDepartmentInput[]
  createMany?: Prisma.EmailScanCreateManyDepartmentInputEnvelope
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
}

export type EmailScanUpdateManyWithoutDepartmentNestedInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutDepartmentInput, Prisma.EmailScanUncheckedCreateWithoutDepartmentInput> | Prisma.EmailScanCreateWithoutDepartmentInput[] | Prisma.EmailScanUncheckedCreateWithoutDepartmentInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutDepartmentInput | Prisma.EmailScanCreateOrConnectWithoutDepartmentInput[]
  upsert?: Prisma.EmailScanUpsertWithWhereUniqueWithoutDepartmentInput | Prisma.EmailScanUpsertWithWhereUniqueWithoutDepartmentInput[]
  createMany?: Prisma.EmailScanCreateManyDepartmentInputEnvelope
  set?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  disconnect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  delete?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  update?: Prisma.EmailScanUpdateWithWhereUniqueWithoutDepartmentInput | Prisma.EmailScanUpdateWithWhereUniqueWithoutDepartmentInput[]
  updateMany?: Prisma.EmailScanUpdateManyWithWhereWithoutDepartmentInput | Prisma.EmailScanUpdateManyWithWhereWithoutDepartmentInput[]
  deleteMany?: Prisma.EmailScanScalarWhereInput | Prisma.EmailScanScalarWhereInput[]
}

export type EmailScanUncheckedUpdateManyWithoutDepartmentNestedInput = {
  create?: Prisma.XOR<Prisma.EmailScanCreateWithoutDepartmentInput, Prisma.EmailScanUncheckedCreateWithoutDepartmentInput> | Prisma.EmailScanCreateWithoutDepartmentInput[] | Prisma.EmailScanUncheckedCreateWithoutDepartmentInput[]
  connectOrCreate?: Prisma.EmailScanCreateOrConnectWithoutDepartmentInput | Prisma.EmailScanCreateOrConnectWithoutDepartmentInput[]
  upsert?: Prisma.EmailScanUpsertWithWhereUniqueWithoutDepartmentInput | Prisma.EmailScanUpsertWithWhereUniqueWithoutDepartmentInput[]
  createMany?: Prisma.EmailScanCreateManyDepartmentInputEnvelope
  set?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  disconnect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  delete?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  connect?: Prisma.EmailScanWhereUniqueInput | Prisma.EmailScanWhereUniqueInput[]
  update?: Prisma.EmailScanUpdateWithWhereUniqueWithoutDepartmentInput | Prisma.EmailScanUpdateWithWhereUniqueWithoutDepartmentInput[]
  updateMany?: Prisma.EmailScanUpdateManyWithWhereWithoutDepartmentInput | Prisma.EmailScanUpdateManyWithWhereWithoutDepartmentInput[]
  deleteMany?: Prisma.EmailScanScalarWhereInput | Prisma.EmailScanScalarWhereInput[]
}

export type EmailScanCreateWithoutUserInput = {
  id?: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
  department: Prisma.DepartmentCreateNestedOneWithoutScansInput
  actions?: Prisma.UserActionCreateNestedManyWithoutEmailScanInput
}

export type EmailScanUncheckedCreateWithoutUserInput = {
  id?: string
  departmentId: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
  actions?: Prisma.UserActionUncheckedCreateNestedManyWithoutEmailScanInput
}

export type EmailScanCreateOrConnectWithoutUserInput = {
  where: Prisma.EmailScanWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailScanCreateWithoutUserInput, Prisma.EmailScanUncheckedCreateWithoutUserInput>
}

export type EmailScanCreateManyUserInputEnvelope = {
  data: Prisma.EmailScanCreateManyUserInput | Prisma.EmailScanCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type EmailScanUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.EmailScanWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailScanUpdateWithoutUserInput, Prisma.EmailScanUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.EmailScanCreateWithoutUserInput, Prisma.EmailScanUncheckedCreateWithoutUserInput>
}

export type EmailScanUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.EmailScanWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailScanUpdateWithoutUserInput, Prisma.EmailScanUncheckedUpdateWithoutUserInput>
}

export type EmailScanUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.EmailScanScalarWhereInput
  data: Prisma.XOR<Prisma.EmailScanUpdateManyMutationInput, Prisma.EmailScanUncheckedUpdateManyWithoutUserInput>
}

export type EmailScanScalarWhereInput = {
  AND?: Prisma.EmailScanScalarWhereInput | Prisma.EmailScanScalarWhereInput[]
  OR?: Prisma.EmailScanScalarWhereInput[]
  NOT?: Prisma.EmailScanScalarWhereInput | Prisma.EmailScanScalarWhereInput[]
  id?: Prisma.StringFilter<"EmailScan"> | string
  userId?: Prisma.StringFilter<"EmailScan"> | string
  departmentId?: Prisma.StringFilter<"EmailScan"> | string
  emailSubject?: Prisma.StringFilter<"EmailScan"> | string
  emailSender?: Prisma.StringFilter<"EmailScan"> | string
  detectedAt?: Prisma.DateTimeFilter<"EmailScan"> | Date | string
  isPhishing?: Prisma.BoolFilter<"EmailScan"> | boolean
  detectedBy?: Prisma.StringFilter<"EmailScan"> | string
  links?: Prisma.StringNullableListFilter<"EmailScan">
}

export type EmailScanCreateWithoutActionsInput = {
  id?: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
  user: Prisma.UserCreateNestedOneWithoutEmailScansInput
  department: Prisma.DepartmentCreateNestedOneWithoutScansInput
}

export type EmailScanUncheckedCreateWithoutActionsInput = {
  id?: string
  userId: string
  departmentId: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
}

export type EmailScanCreateOrConnectWithoutActionsInput = {
  where: Prisma.EmailScanWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailScanCreateWithoutActionsInput, Prisma.EmailScanUncheckedCreateWithoutActionsInput>
}

export type EmailScanUpsertWithoutActionsInput = {
  update: Prisma.XOR<Prisma.EmailScanUpdateWithoutActionsInput, Prisma.EmailScanUncheckedUpdateWithoutActionsInput>
  create: Prisma.XOR<Prisma.EmailScanCreateWithoutActionsInput, Prisma.EmailScanUncheckedCreateWithoutActionsInput>
  where?: Prisma.EmailScanWhereInput
}

export type EmailScanUpdateToOneWithWhereWithoutActionsInput = {
  where?: Prisma.EmailScanWhereInput
  data: Prisma.XOR<Prisma.EmailScanUpdateWithoutActionsInput, Prisma.EmailScanUncheckedUpdateWithoutActionsInput>
}

export type EmailScanUpdateWithoutActionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
  user?: Prisma.UserUpdateOneRequiredWithoutEmailScansNestedInput
  department?: Prisma.DepartmentUpdateOneRequiredWithoutScansNestedInput
}

export type EmailScanUncheckedUpdateWithoutActionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  departmentId?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
}

export type EmailScanCreateWithoutDepartmentInput = {
  id?: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
  user: Prisma.UserCreateNestedOneWithoutEmailScansInput
  actions?: Prisma.UserActionCreateNestedManyWithoutEmailScanInput
}

export type EmailScanUncheckedCreateWithoutDepartmentInput = {
  id?: string
  userId: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
  actions?: Prisma.UserActionUncheckedCreateNestedManyWithoutEmailScanInput
}

export type EmailScanCreateOrConnectWithoutDepartmentInput = {
  where: Prisma.EmailScanWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailScanCreateWithoutDepartmentInput, Prisma.EmailScanUncheckedCreateWithoutDepartmentInput>
}

export type EmailScanCreateManyDepartmentInputEnvelope = {
  data: Prisma.EmailScanCreateManyDepartmentInput | Prisma.EmailScanCreateManyDepartmentInput[]
  skipDuplicates?: boolean
}

export type EmailScanUpsertWithWhereUniqueWithoutDepartmentInput = {
  where: Prisma.EmailScanWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailScanUpdateWithoutDepartmentInput, Prisma.EmailScanUncheckedUpdateWithoutDepartmentInput>
  create: Prisma.XOR<Prisma.EmailScanCreateWithoutDepartmentInput, Prisma.EmailScanUncheckedCreateWithoutDepartmentInput>
}

export type EmailScanUpdateWithWhereUniqueWithoutDepartmentInput = {
  where: Prisma.EmailScanWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailScanUpdateWithoutDepartmentInput, Prisma.EmailScanUncheckedUpdateWithoutDepartmentInput>
}

export type EmailScanUpdateManyWithWhereWithoutDepartmentInput = {
  where: Prisma.EmailScanScalarWhereInput
  data: Prisma.XOR<Prisma.EmailScanUpdateManyMutationInput, Prisma.EmailScanUncheckedUpdateManyWithoutDepartmentInput>
}

export type EmailScanCreateManyUserInput = {
  id?: string
  departmentId: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
}

export type EmailScanUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
  department?: Prisma.DepartmentUpdateOneRequiredWithoutScansNestedInput
  actions?: Prisma.UserActionUpdateManyWithoutEmailScanNestedInput
}

export type EmailScanUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  departmentId?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
  actions?: Prisma.UserActionUncheckedUpdateManyWithoutEmailScanNestedInput
}

export type EmailScanUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  departmentId?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
}

export type EmailScanCreateManyDepartmentInput = {
  id?: string
  userId: string
  emailSubject: string
  emailSender: string
  detectedAt?: Date | string
  isPhishing: boolean
  detectedBy: string
  links?: Prisma.EmailScanCreatelinksInput | string[]
}

export type EmailScanUpdateWithoutDepartmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
  user?: Prisma.UserUpdateOneRequiredWithoutEmailScansNestedInput
  actions?: Prisma.UserActionUpdateManyWithoutEmailScanNestedInput
}

export type EmailScanUncheckedUpdateWithoutDepartmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
  actions?: Prisma.UserActionUncheckedUpdateManyWithoutEmailScanNestedInput
}

export type EmailScanUncheckedUpdateManyWithoutDepartmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  emailSubject?: Prisma.StringFieldUpdateOperationsInput | string
  emailSender?: Prisma.StringFieldUpdateOperationsInput | string
  detectedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  isPhishing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  detectedBy?: Prisma.StringFieldUpdateOperationsInput | string
  links?: Prisma.EmailScanUpdatelinksInput | string[]
}


/**
 * Count Type EmailScanCountOutputType
 */

export type EmailScanCountOutputType = {
  actions: number
}

export type EmailScanCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actions?: boolean | EmailScanCountOutputTypeCountActionsArgs
}

/**
 * EmailScanCountOutputType without action
 */
export type EmailScanCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScanCountOutputType
   */
  select?: Prisma.EmailScanCountOutputTypeSelect<ExtArgs> | null
}

/**
 * EmailScanCountOutputType without action
 */
export type EmailScanCountOutputTypeCountActionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserActionWhereInput
}


export type EmailScanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  departmentId?: boolean
  emailSubject?: boolean
  emailSender?: boolean
  detectedAt?: boolean
  isPhishing?: boolean
  detectedBy?: boolean
  links?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  department?: boolean | Prisma.DepartmentDefaultArgs<ExtArgs>
  actions?: boolean | Prisma.EmailScan$actionsArgs<ExtArgs>
  _count?: boolean | Prisma.EmailScanCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailScan"]>

export type EmailScanSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  departmentId?: boolean
  emailSubject?: boolean
  emailSender?: boolean
  detectedAt?: boolean
  isPhishing?: boolean
  detectedBy?: boolean
  links?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  department?: boolean | Prisma.DepartmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailScan"]>

export type EmailScanSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  departmentId?: boolean
  emailSubject?: boolean
  emailSender?: boolean
  detectedAt?: boolean
  isPhishing?: boolean
  detectedBy?: boolean
  links?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  department?: boolean | Prisma.DepartmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailScan"]>

export type EmailScanSelectScalar = {
  id?: boolean
  userId?: boolean
  departmentId?: boolean
  emailSubject?: boolean
  emailSender?: boolean
  detectedAt?: boolean
  isPhishing?: boolean
  detectedBy?: boolean
  links?: boolean
}

export type EmailScanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "departmentId" | "emailSubject" | "emailSender" | "detectedAt" | "isPhishing" | "detectedBy" | "links", ExtArgs["result"]["emailScan"]>
export type EmailScanInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  department?: boolean | Prisma.DepartmentDefaultArgs<ExtArgs>
  actions?: boolean | Prisma.EmailScan$actionsArgs<ExtArgs>
  _count?: boolean | Prisma.EmailScanCountOutputTypeDefaultArgs<ExtArgs>
}
export type EmailScanIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  department?: boolean | Prisma.DepartmentDefaultArgs<ExtArgs>
}
export type EmailScanIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  department?: boolean | Prisma.DepartmentDefaultArgs<ExtArgs>
}

export type $EmailScanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EmailScan"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    department: Prisma.$DepartmentPayload<ExtArgs>
    actions: Prisma.$UserActionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    departmentId: string
    emailSubject: string
    emailSender: string
    detectedAt: Date
    isPhishing: boolean
    detectedBy: string
    links: string[]
  }, ExtArgs["result"]["emailScan"]>
  composites: {}
}

export type EmailScanGetPayload<S extends boolean | null | undefined | EmailScanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmailScanPayload, S>

export type EmailScanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmailScanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmailScanCountAggregateInputType | true
  }

export interface EmailScanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EmailScan'], meta: { name: 'EmailScan' } }
  /**
   * Find zero or one EmailScan that matches the filter.
   * @param {EmailScanFindUniqueArgs} args - Arguments to find a EmailScan
   * @example
   * // Get one EmailScan
   * const emailScan = await prisma.emailScan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmailScanFindUniqueArgs>(args: Prisma.SelectSubset<T, EmailScanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EmailScan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmailScanFindUniqueOrThrowArgs} args - Arguments to find a EmailScan
   * @example
   * // Get one EmailScan
   * const emailScan = await prisma.emailScan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmailScanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmailScanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailScan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailScanFindFirstArgs} args - Arguments to find a EmailScan
   * @example
   * // Get one EmailScan
   * const emailScan = await prisma.emailScan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmailScanFindFirstArgs>(args?: Prisma.SelectSubset<T, EmailScanFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailScan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailScanFindFirstOrThrowArgs} args - Arguments to find a EmailScan
   * @example
   * // Get one EmailScan
   * const emailScan = await prisma.emailScan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmailScanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmailScanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EmailScans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailScanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EmailScans
   * const emailScans = await prisma.emailScan.findMany()
   * 
   * // Get first 10 EmailScans
   * const emailScans = await prisma.emailScan.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const emailScanWithIdOnly = await prisma.emailScan.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmailScanFindManyArgs>(args?: Prisma.SelectSubset<T, EmailScanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EmailScan.
   * @param {EmailScanCreateArgs} args - Arguments to create a EmailScan.
   * @example
   * // Create one EmailScan
   * const EmailScan = await prisma.emailScan.create({
   *   data: {
   *     // ... data to create a EmailScan
   *   }
   * })
   * 
   */
  create<T extends EmailScanCreateArgs>(args: Prisma.SelectSubset<T, EmailScanCreateArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EmailScans.
   * @param {EmailScanCreateManyArgs} args - Arguments to create many EmailScans.
   * @example
   * // Create many EmailScans
   * const emailScan = await prisma.emailScan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmailScanCreateManyArgs>(args?: Prisma.SelectSubset<T, EmailScanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EmailScans and returns the data saved in the database.
   * @param {EmailScanCreateManyAndReturnArgs} args - Arguments to create many EmailScans.
   * @example
   * // Create many EmailScans
   * const emailScan = await prisma.emailScan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EmailScans and only return the `id`
   * const emailScanWithIdOnly = await prisma.emailScan.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmailScanCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmailScanCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EmailScan.
   * @param {EmailScanDeleteArgs} args - Arguments to delete one EmailScan.
   * @example
   * // Delete one EmailScan
   * const EmailScan = await prisma.emailScan.delete({
   *   where: {
   *     // ... filter to delete one EmailScan
   *   }
   * })
   * 
   */
  delete<T extends EmailScanDeleteArgs>(args: Prisma.SelectSubset<T, EmailScanDeleteArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EmailScan.
   * @param {EmailScanUpdateArgs} args - Arguments to update one EmailScan.
   * @example
   * // Update one EmailScan
   * const emailScan = await prisma.emailScan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmailScanUpdateArgs>(args: Prisma.SelectSubset<T, EmailScanUpdateArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EmailScans.
   * @param {EmailScanDeleteManyArgs} args - Arguments to filter EmailScans to delete.
   * @example
   * // Delete a few EmailScans
   * const { count } = await prisma.emailScan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmailScanDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmailScanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmailScans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailScanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EmailScans
   * const emailScan = await prisma.emailScan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmailScanUpdateManyArgs>(args: Prisma.SelectSubset<T, EmailScanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmailScans and returns the data updated in the database.
   * @param {EmailScanUpdateManyAndReturnArgs} args - Arguments to update many EmailScans.
   * @example
   * // Update many EmailScans
   * const emailScan = await prisma.emailScan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EmailScans and only return the `id`
   * const emailScanWithIdOnly = await prisma.emailScan.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmailScanUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmailScanUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EmailScan.
   * @param {EmailScanUpsertArgs} args - Arguments to update or create a EmailScan.
   * @example
   * // Update or create a EmailScan
   * const emailScan = await prisma.emailScan.upsert({
   *   create: {
   *     // ... data to create a EmailScan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EmailScan we want to update
   *   }
   * })
   */
  upsert<T extends EmailScanUpsertArgs>(args: Prisma.SelectSubset<T, EmailScanUpsertArgs<ExtArgs>>): Prisma.Prisma__EmailScanClient<runtime.Types.Result.GetResult<Prisma.$EmailScanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EmailScans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailScanCountArgs} args - Arguments to filter EmailScans to count.
   * @example
   * // Count the number of EmailScans
   * const count = await prisma.emailScan.count({
   *   where: {
   *     // ... the filter for the EmailScans we want to count
   *   }
   * })
  **/
  count<T extends EmailScanCountArgs>(
    args?: Prisma.Subset<T, EmailScanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmailScanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EmailScan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailScanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmailScanAggregateArgs>(args: Prisma.Subset<T, EmailScanAggregateArgs>): Prisma.PrismaPromise<GetEmailScanAggregateType<T>>

  /**
   * Group by EmailScan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailScanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmailScanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmailScanGroupByArgs['orderBy'] }
      : { orderBy?: EmailScanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmailScanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmailScanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EmailScan model
 */
readonly fields: EmailScanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EmailScan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmailScanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  department<T extends Prisma.DepartmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DepartmentDefaultArgs<ExtArgs>>): Prisma.Prisma__DepartmentClient<runtime.Types.Result.GetResult<Prisma.$DepartmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  actions<T extends Prisma.EmailScan$actionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EmailScan$actionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserActionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EmailScan model
 */
export interface EmailScanFieldRefs {
  readonly id: Prisma.FieldRef<"EmailScan", 'String'>
  readonly userId: Prisma.FieldRef<"EmailScan", 'String'>
  readonly departmentId: Prisma.FieldRef<"EmailScan", 'String'>
  readonly emailSubject: Prisma.FieldRef<"EmailScan", 'String'>
  readonly emailSender: Prisma.FieldRef<"EmailScan", 'String'>
  readonly detectedAt: Prisma.FieldRef<"EmailScan", 'DateTime'>
  readonly isPhishing: Prisma.FieldRef<"EmailScan", 'Boolean'>
  readonly detectedBy: Prisma.FieldRef<"EmailScan", 'String'>
  readonly links: Prisma.FieldRef<"EmailScan", 'String[]'>
}
    

// Custom InputTypes
/**
 * EmailScan findUnique
 */
export type EmailScanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * Filter, which EmailScan to fetch.
   */
  where: Prisma.EmailScanWhereUniqueInput
}

/**
 * EmailScan findUniqueOrThrow
 */
export type EmailScanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * Filter, which EmailScan to fetch.
   */
  where: Prisma.EmailScanWhereUniqueInput
}

/**
 * EmailScan findFirst
 */
export type EmailScanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * Filter, which EmailScan to fetch.
   */
  where?: Prisma.EmailScanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailScans to fetch.
   */
  orderBy?: Prisma.EmailScanOrderByWithRelationInput | Prisma.EmailScanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailScans.
   */
  cursor?: Prisma.EmailScanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailScans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailScans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailScans.
   */
  distinct?: Prisma.EmailScanScalarFieldEnum | Prisma.EmailScanScalarFieldEnum[]
}

/**
 * EmailScan findFirstOrThrow
 */
export type EmailScanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * Filter, which EmailScan to fetch.
   */
  where?: Prisma.EmailScanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailScans to fetch.
   */
  orderBy?: Prisma.EmailScanOrderByWithRelationInput | Prisma.EmailScanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailScans.
   */
  cursor?: Prisma.EmailScanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailScans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailScans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailScans.
   */
  distinct?: Prisma.EmailScanScalarFieldEnum | Prisma.EmailScanScalarFieldEnum[]
}

/**
 * EmailScan findMany
 */
export type EmailScanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * Filter, which EmailScans to fetch.
   */
  where?: Prisma.EmailScanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailScans to fetch.
   */
  orderBy?: Prisma.EmailScanOrderByWithRelationInput | Prisma.EmailScanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EmailScans.
   */
  cursor?: Prisma.EmailScanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailScans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailScans.
   */
  skip?: number
  distinct?: Prisma.EmailScanScalarFieldEnum | Prisma.EmailScanScalarFieldEnum[]
}

/**
 * EmailScan create
 */
export type EmailScanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * The data needed to create a EmailScan.
   */
  data: Prisma.XOR<Prisma.EmailScanCreateInput, Prisma.EmailScanUncheckedCreateInput>
}

/**
 * EmailScan createMany
 */
export type EmailScanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EmailScans.
   */
  data: Prisma.EmailScanCreateManyInput | Prisma.EmailScanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EmailScan createManyAndReturn
 */
export type EmailScanCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * The data used to create many EmailScans.
   */
  data: Prisma.EmailScanCreateManyInput | Prisma.EmailScanCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EmailScan update
 */
export type EmailScanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * The data needed to update a EmailScan.
   */
  data: Prisma.XOR<Prisma.EmailScanUpdateInput, Prisma.EmailScanUncheckedUpdateInput>
  /**
   * Choose, which EmailScan to update.
   */
  where: Prisma.EmailScanWhereUniqueInput
}

/**
 * EmailScan updateMany
 */
export type EmailScanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EmailScans.
   */
  data: Prisma.XOR<Prisma.EmailScanUpdateManyMutationInput, Prisma.EmailScanUncheckedUpdateManyInput>
  /**
   * Filter which EmailScans to update
   */
  where?: Prisma.EmailScanWhereInput
  /**
   * Limit how many EmailScans to update.
   */
  limit?: number
}

/**
 * EmailScan updateManyAndReturn
 */
export type EmailScanUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * The data used to update EmailScans.
   */
  data: Prisma.XOR<Prisma.EmailScanUpdateManyMutationInput, Prisma.EmailScanUncheckedUpdateManyInput>
  /**
   * Filter which EmailScans to update
   */
  where?: Prisma.EmailScanWhereInput
  /**
   * Limit how many EmailScans to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EmailScan upsert
 */
export type EmailScanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * The filter to search for the EmailScan to update in case it exists.
   */
  where: Prisma.EmailScanWhereUniqueInput
  /**
   * In case the EmailScan found by the `where` argument doesn't exist, create a new EmailScan with this data.
   */
  create: Prisma.XOR<Prisma.EmailScanCreateInput, Prisma.EmailScanUncheckedCreateInput>
  /**
   * In case the EmailScan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmailScanUpdateInput, Prisma.EmailScanUncheckedUpdateInput>
}

/**
 * EmailScan delete
 */
export type EmailScanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
  /**
   * Filter which EmailScan to delete.
   */
  where: Prisma.EmailScanWhereUniqueInput
}

/**
 * EmailScan deleteMany
 */
export type EmailScanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailScans to delete
   */
  where?: Prisma.EmailScanWhereInput
  /**
   * Limit how many EmailScans to delete.
   */
  limit?: number
}

/**
 * EmailScan.actions
 */
export type EmailScan$actionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserAction
   */
  select?: Prisma.UserActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserAction
   */
  omit?: Prisma.UserActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserActionInclude<ExtArgs> | null
  where?: Prisma.UserActionWhereInput
  orderBy?: Prisma.UserActionOrderByWithRelationInput | Prisma.UserActionOrderByWithRelationInput[]
  cursor?: Prisma.UserActionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserActionScalarFieldEnum | Prisma.UserActionScalarFieldEnum[]
}

/**
 * EmailScan without action
 */
export type EmailScanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailScan
   */
  select?: Prisma.EmailScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailScan
   */
  omit?: Prisma.EmailScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailScanInclude<ExtArgs> | null
}
