
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EmailDeliveryLog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EmailDeliveryLog
 * 
 */
export type EmailDeliveryLogModel = runtime.Types.Result.DefaultSelection<Prisma.$EmailDeliveryLogPayload>

export type AggregateEmailDeliveryLog = {
  _count: EmailDeliveryLogCountAggregateOutputType | null
  _min: EmailDeliveryLogMinAggregateOutputType | null
  _max: EmailDeliveryLogMaxAggregateOutputType | null
}

export type EmailDeliveryLogMinAggregateOutputType = {
  id: string | null
  inviteId: string | null
  organizationId: string | null
  recipientEmail: string | null
  channel: string | null
  status: $Enums.DeliveryStatus | null
  providerMessageId: string | null
  error: string | null
  createdAt: Date | null
}

export type EmailDeliveryLogMaxAggregateOutputType = {
  id: string | null
  inviteId: string | null
  organizationId: string | null
  recipientEmail: string | null
  channel: string | null
  status: $Enums.DeliveryStatus | null
  providerMessageId: string | null
  error: string | null
  createdAt: Date | null
}

export type EmailDeliveryLogCountAggregateOutputType = {
  id: number
  inviteId: number
  organizationId: number
  recipientEmail: number
  channel: number
  status: number
  providerMessageId: number
  error: number
  metadata: number
  createdAt: number
  _all: number
}


export type EmailDeliveryLogMinAggregateInputType = {
  id?: true
  inviteId?: true
  organizationId?: true
  recipientEmail?: true
  channel?: true
  status?: true
  providerMessageId?: true
  error?: true
  createdAt?: true
}

export type EmailDeliveryLogMaxAggregateInputType = {
  id?: true
  inviteId?: true
  organizationId?: true
  recipientEmail?: true
  channel?: true
  status?: true
  providerMessageId?: true
  error?: true
  createdAt?: true
}

export type EmailDeliveryLogCountAggregateInputType = {
  id?: true
  inviteId?: true
  organizationId?: true
  recipientEmail?: true
  channel?: true
  status?: true
  providerMessageId?: true
  error?: true
  metadata?: true
  createdAt?: true
  _all?: true
}

export type EmailDeliveryLogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailDeliveryLog to aggregate.
   */
  where?: Prisma.EmailDeliveryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailDeliveryLogs to fetch.
   */
  orderBy?: Prisma.EmailDeliveryLogOrderByWithRelationInput | Prisma.EmailDeliveryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmailDeliveryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailDeliveryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailDeliveryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EmailDeliveryLogs
  **/
  _count?: true | EmailDeliveryLogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmailDeliveryLogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmailDeliveryLogMaxAggregateInputType
}

export type GetEmailDeliveryLogAggregateType<T extends EmailDeliveryLogAggregateArgs> = {
      [P in keyof T & keyof AggregateEmailDeliveryLog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmailDeliveryLog[P]>
    : Prisma.GetScalarType<T[P], AggregateEmailDeliveryLog[P]>
}




export type EmailDeliveryLogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmailDeliveryLogWhereInput
  orderBy?: Prisma.EmailDeliveryLogOrderByWithAggregationInput | Prisma.EmailDeliveryLogOrderByWithAggregationInput[]
  by: Prisma.EmailDeliveryLogScalarFieldEnum[] | Prisma.EmailDeliveryLogScalarFieldEnum
  having?: Prisma.EmailDeliveryLogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmailDeliveryLogCountAggregateInputType | true
  _min?: EmailDeliveryLogMinAggregateInputType
  _max?: EmailDeliveryLogMaxAggregateInputType
}

export type EmailDeliveryLogGroupByOutputType = {
  id: string
  inviteId: string | null
  organizationId: string
  recipientEmail: string
  channel: string
  status: $Enums.DeliveryStatus
  providerMessageId: string | null
  error: string | null
  metadata: runtime.JsonValue | null
  createdAt: Date
  _count: EmailDeliveryLogCountAggregateOutputType | null
  _min: EmailDeliveryLogMinAggregateOutputType | null
  _max: EmailDeliveryLogMaxAggregateOutputType | null
}

export type GetEmailDeliveryLogGroupByPayload<T extends EmailDeliveryLogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmailDeliveryLogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmailDeliveryLogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmailDeliveryLogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmailDeliveryLogGroupByOutputType[P]>
      }
    >
  >



export type EmailDeliveryLogWhereInput = {
  AND?: Prisma.EmailDeliveryLogWhereInput | Prisma.EmailDeliveryLogWhereInput[]
  OR?: Prisma.EmailDeliveryLogWhereInput[]
  NOT?: Prisma.EmailDeliveryLogWhereInput | Prisma.EmailDeliveryLogWhereInput[]
  id?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  inviteId?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  organizationId?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  recipientEmail?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  channel?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  status?: Prisma.EnumDeliveryStatusFilter<"EmailDeliveryLog"> | $Enums.DeliveryStatus
  providerMessageId?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  error?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  metadata?: Prisma.JsonNullableFilter<"EmailDeliveryLog">
  createdAt?: Prisma.DateTimeFilter<"EmailDeliveryLog"> | Date | string
  invite?: Prisma.XOR<Prisma.OrganizationInviteNullableScalarRelationFilter, Prisma.OrganizationInviteWhereInput> | null
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
}

export type EmailDeliveryLogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  inviteId?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  recipientEmail?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  status?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  invite?: Prisma.OrganizationInviteOrderByWithRelationInput
  organization?: Prisma.OrganizationOrderByWithRelationInput
}

export type EmailDeliveryLogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EmailDeliveryLogWhereInput | Prisma.EmailDeliveryLogWhereInput[]
  OR?: Prisma.EmailDeliveryLogWhereInput[]
  NOT?: Prisma.EmailDeliveryLogWhereInput | Prisma.EmailDeliveryLogWhereInput[]
  inviteId?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  organizationId?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  recipientEmail?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  channel?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  status?: Prisma.EnumDeliveryStatusFilter<"EmailDeliveryLog"> | $Enums.DeliveryStatus
  providerMessageId?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  error?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  metadata?: Prisma.JsonNullableFilter<"EmailDeliveryLog">
  createdAt?: Prisma.DateTimeFilter<"EmailDeliveryLog"> | Date | string
  invite?: Prisma.XOR<Prisma.OrganizationInviteNullableScalarRelationFilter, Prisma.OrganizationInviteWhereInput> | null
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
}, "id">

export type EmailDeliveryLogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  inviteId?: Prisma.SortOrderInput | Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  recipientEmail?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  status?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.EmailDeliveryLogCountOrderByAggregateInput
  _max?: Prisma.EmailDeliveryLogMaxOrderByAggregateInput
  _min?: Prisma.EmailDeliveryLogMinOrderByAggregateInput
}

export type EmailDeliveryLogScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmailDeliveryLogScalarWhereWithAggregatesInput | Prisma.EmailDeliveryLogScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmailDeliveryLogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmailDeliveryLogScalarWhereWithAggregatesInput | Prisma.EmailDeliveryLogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EmailDeliveryLog"> | string
  inviteId?: Prisma.StringNullableWithAggregatesFilter<"EmailDeliveryLog"> | string | null
  organizationId?: Prisma.StringWithAggregatesFilter<"EmailDeliveryLog"> | string
  recipientEmail?: Prisma.StringWithAggregatesFilter<"EmailDeliveryLog"> | string
  channel?: Prisma.StringWithAggregatesFilter<"EmailDeliveryLog"> | string
  status?: Prisma.EnumDeliveryStatusWithAggregatesFilter<"EmailDeliveryLog"> | $Enums.DeliveryStatus
  providerMessageId?: Prisma.StringNullableWithAggregatesFilter<"EmailDeliveryLog"> | string | null
  error?: Prisma.StringNullableWithAggregatesFilter<"EmailDeliveryLog"> | string | null
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"EmailDeliveryLog">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"EmailDeliveryLog"> | Date | string
}

export type EmailDeliveryLogCreateInput = {
  id?: string
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  invite?: Prisma.OrganizationInviteCreateNestedOneWithoutEmailLogsInput
  organization: Prisma.OrganizationCreateNestedOneWithoutEmailDeliveryLogsInput
}

export type EmailDeliveryLogUncheckedCreateInput = {
  id?: string
  inviteId?: string | null
  organizationId: string
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EmailDeliveryLogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invite?: Prisma.OrganizationInviteUpdateOneWithoutEmailLogsNestedInput
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutEmailDeliveryLogsNestedInput
}

export type EmailDeliveryLogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inviteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailDeliveryLogCreateManyInput = {
  id?: string
  inviteId?: string | null
  organizationId: string
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EmailDeliveryLogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailDeliveryLogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inviteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailDeliveryLogListRelationFilter = {
  every?: Prisma.EmailDeliveryLogWhereInput
  some?: Prisma.EmailDeliveryLogWhereInput
  none?: Prisma.EmailDeliveryLogWhereInput
}

export type EmailDeliveryLogOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmailDeliveryLogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  inviteId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  recipientEmail?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  status?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  error?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EmailDeliveryLogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  inviteId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  recipientEmail?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  status?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EmailDeliveryLogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  inviteId?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  recipientEmail?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  status?: Prisma.SortOrder
  providerMessageId?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type EmailDeliveryLogCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput> | Prisma.EmailDeliveryLogCreateWithoutOrganizationInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyOrganizationInputEnvelope
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
}

export type EmailDeliveryLogUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput> | Prisma.EmailDeliveryLogCreateWithoutOrganizationInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyOrganizationInputEnvelope
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
}

export type EmailDeliveryLogUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput> | Prisma.EmailDeliveryLogCreateWithoutOrganizationInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyOrganizationInputEnvelope
  set?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  disconnect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  delete?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  update?: Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutOrganizationInput | Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.EmailDeliveryLogScalarWhereInput | Prisma.EmailDeliveryLogScalarWhereInput[]
}

export type EmailDeliveryLogUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput> | Prisma.EmailDeliveryLogCreateWithoutOrganizationInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyOrganizationInputEnvelope
  set?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  disconnect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  delete?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  update?: Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutOrganizationInput | Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.EmailDeliveryLogScalarWhereInput | Prisma.EmailDeliveryLogScalarWhereInput[]
}

export type EmailDeliveryLogCreateNestedManyWithoutInviteInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput> | Prisma.EmailDeliveryLogCreateWithoutInviteInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyInviteInputEnvelope
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
}

export type EmailDeliveryLogUncheckedCreateNestedManyWithoutInviteInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput> | Prisma.EmailDeliveryLogCreateWithoutInviteInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyInviteInputEnvelope
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
}

export type EmailDeliveryLogUpdateManyWithoutInviteNestedInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput> | Prisma.EmailDeliveryLogCreateWithoutInviteInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput[]
  upsert?: Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutInviteInput | Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutInviteInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyInviteInputEnvelope
  set?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  disconnect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  delete?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  update?: Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutInviteInput | Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutInviteInput[]
  updateMany?: Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutInviteInput | Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutInviteInput[]
  deleteMany?: Prisma.EmailDeliveryLogScalarWhereInput | Prisma.EmailDeliveryLogScalarWhereInput[]
}

export type EmailDeliveryLogUncheckedUpdateManyWithoutInviteNestedInput = {
  create?: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput> | Prisma.EmailDeliveryLogCreateWithoutInviteInput[] | Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput[]
  connectOrCreate?: Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput | Prisma.EmailDeliveryLogCreateOrConnectWithoutInviteInput[]
  upsert?: Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutInviteInput | Prisma.EmailDeliveryLogUpsertWithWhereUniqueWithoutInviteInput[]
  createMany?: Prisma.EmailDeliveryLogCreateManyInviteInputEnvelope
  set?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  disconnect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  delete?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  connect?: Prisma.EmailDeliveryLogWhereUniqueInput | Prisma.EmailDeliveryLogWhereUniqueInput[]
  update?: Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutInviteInput | Prisma.EmailDeliveryLogUpdateWithWhereUniqueWithoutInviteInput[]
  updateMany?: Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutInviteInput | Prisma.EmailDeliveryLogUpdateManyWithWhereWithoutInviteInput[]
  deleteMany?: Prisma.EmailDeliveryLogScalarWhereInput | Prisma.EmailDeliveryLogScalarWhereInput[]
}

export type EnumDeliveryStatusFieldUpdateOperationsInput = {
  set?: $Enums.DeliveryStatus
}

export type EmailDeliveryLogCreateWithoutOrganizationInput = {
  id?: string
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  invite?: Prisma.OrganizationInviteCreateNestedOneWithoutEmailLogsInput
}

export type EmailDeliveryLogUncheckedCreateWithoutOrganizationInput = {
  id?: string
  inviteId?: string | null
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EmailDeliveryLogCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.EmailDeliveryLogWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput>
}

export type EmailDeliveryLogCreateManyOrganizationInputEnvelope = {
  data: Prisma.EmailDeliveryLogCreateManyOrganizationInput | Prisma.EmailDeliveryLogCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type EmailDeliveryLogUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.EmailDeliveryLogWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailDeliveryLogUpdateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutOrganizationInput>
}

export type EmailDeliveryLogUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.EmailDeliveryLogWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailDeliveryLogUpdateWithoutOrganizationInput, Prisma.EmailDeliveryLogUncheckedUpdateWithoutOrganizationInput>
}

export type EmailDeliveryLogUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.EmailDeliveryLogScalarWhereInput
  data: Prisma.XOR<Prisma.EmailDeliveryLogUpdateManyMutationInput, Prisma.EmailDeliveryLogUncheckedUpdateManyWithoutOrganizationInput>
}

export type EmailDeliveryLogScalarWhereInput = {
  AND?: Prisma.EmailDeliveryLogScalarWhereInput | Prisma.EmailDeliveryLogScalarWhereInput[]
  OR?: Prisma.EmailDeliveryLogScalarWhereInput[]
  NOT?: Prisma.EmailDeliveryLogScalarWhereInput | Prisma.EmailDeliveryLogScalarWhereInput[]
  id?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  inviteId?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  organizationId?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  recipientEmail?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  channel?: Prisma.StringFilter<"EmailDeliveryLog"> | string
  status?: Prisma.EnumDeliveryStatusFilter<"EmailDeliveryLog"> | $Enums.DeliveryStatus
  providerMessageId?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  error?: Prisma.StringNullableFilter<"EmailDeliveryLog"> | string | null
  metadata?: Prisma.JsonNullableFilter<"EmailDeliveryLog">
  createdAt?: Prisma.DateTimeFilter<"EmailDeliveryLog"> | Date | string
}

export type EmailDeliveryLogCreateWithoutInviteInput = {
  id?: string
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutEmailDeliveryLogsInput
}

export type EmailDeliveryLogUncheckedCreateWithoutInviteInput = {
  id?: string
  organizationId: string
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EmailDeliveryLogCreateOrConnectWithoutInviteInput = {
  where: Prisma.EmailDeliveryLogWhereUniqueInput
  create: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput>
}

export type EmailDeliveryLogCreateManyInviteInputEnvelope = {
  data: Prisma.EmailDeliveryLogCreateManyInviteInput | Prisma.EmailDeliveryLogCreateManyInviteInput[]
  skipDuplicates?: boolean
}

export type EmailDeliveryLogUpsertWithWhereUniqueWithoutInviteInput = {
  where: Prisma.EmailDeliveryLogWhereUniqueInput
  update: Prisma.XOR<Prisma.EmailDeliveryLogUpdateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedUpdateWithoutInviteInput>
  create: Prisma.XOR<Prisma.EmailDeliveryLogCreateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedCreateWithoutInviteInput>
}

export type EmailDeliveryLogUpdateWithWhereUniqueWithoutInviteInput = {
  where: Prisma.EmailDeliveryLogWhereUniqueInput
  data: Prisma.XOR<Prisma.EmailDeliveryLogUpdateWithoutInviteInput, Prisma.EmailDeliveryLogUncheckedUpdateWithoutInviteInput>
}

export type EmailDeliveryLogUpdateManyWithWhereWithoutInviteInput = {
  where: Prisma.EmailDeliveryLogScalarWhereInput
  data: Prisma.XOR<Prisma.EmailDeliveryLogUpdateManyMutationInput, Prisma.EmailDeliveryLogUncheckedUpdateManyWithoutInviteInput>
}

export type EmailDeliveryLogCreateManyOrganizationInput = {
  id?: string
  inviteId?: string | null
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EmailDeliveryLogUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  invite?: Prisma.OrganizationInviteUpdateOneWithoutEmailLogsNestedInput
}

export type EmailDeliveryLogUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inviteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailDeliveryLogUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  inviteId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailDeliveryLogCreateManyInviteInput = {
  id?: string
  organizationId: string
  recipientEmail: string
  channel?: string
  status: $Enums.DeliveryStatus
  providerMessageId?: string | null
  error?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type EmailDeliveryLogUpdateWithoutInviteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutEmailDeliveryLogsNestedInput
}

export type EmailDeliveryLogUncheckedUpdateWithoutInviteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type EmailDeliveryLogUncheckedUpdateManyWithoutInviteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  recipientEmail?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumDeliveryStatusFieldUpdateOperationsInput | $Enums.DeliveryStatus
  providerMessageId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type EmailDeliveryLogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  inviteId?: boolean
  organizationId?: boolean
  recipientEmail?: boolean
  channel?: boolean
  status?: boolean
  providerMessageId?: boolean
  error?: boolean
  metadata?: boolean
  createdAt?: boolean
  invite?: boolean | Prisma.EmailDeliveryLog$inviteArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailDeliveryLog"]>

export type EmailDeliveryLogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  inviteId?: boolean
  organizationId?: boolean
  recipientEmail?: boolean
  channel?: boolean
  status?: boolean
  providerMessageId?: boolean
  error?: boolean
  metadata?: boolean
  createdAt?: boolean
  invite?: boolean | Prisma.EmailDeliveryLog$inviteArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailDeliveryLog"]>

export type EmailDeliveryLogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  inviteId?: boolean
  organizationId?: boolean
  recipientEmail?: boolean
  channel?: boolean
  status?: boolean
  providerMessageId?: boolean
  error?: boolean
  metadata?: boolean
  createdAt?: boolean
  invite?: boolean | Prisma.EmailDeliveryLog$inviteArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["emailDeliveryLog"]>

export type EmailDeliveryLogSelectScalar = {
  id?: boolean
  inviteId?: boolean
  organizationId?: boolean
  recipientEmail?: boolean
  channel?: boolean
  status?: boolean
  providerMessageId?: boolean
  error?: boolean
  metadata?: boolean
  createdAt?: boolean
}

export type EmailDeliveryLogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "inviteId" | "organizationId" | "recipientEmail" | "channel" | "status" | "providerMessageId" | "error" | "metadata" | "createdAt", ExtArgs["result"]["emailDeliveryLog"]>
export type EmailDeliveryLogInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  invite?: boolean | Prisma.EmailDeliveryLog$inviteArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}
export type EmailDeliveryLogIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  invite?: boolean | Prisma.EmailDeliveryLog$inviteArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}
export type EmailDeliveryLogIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  invite?: boolean | Prisma.EmailDeliveryLog$inviteArgs<ExtArgs>
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}

export type $EmailDeliveryLogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EmailDeliveryLog"
  objects: {
    invite: Prisma.$OrganizationInvitePayload<ExtArgs> | null
    organization: Prisma.$OrganizationPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    inviteId: string | null
    organizationId: string
    recipientEmail: string
    channel: string
    status: $Enums.DeliveryStatus
    providerMessageId: string | null
    error: string | null
    metadata: runtime.JsonValue | null
    createdAt: Date
  }, ExtArgs["result"]["emailDeliveryLog"]>
  composites: {}
}

export type EmailDeliveryLogGetPayload<S extends boolean | null | undefined | EmailDeliveryLogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload, S>

export type EmailDeliveryLogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmailDeliveryLogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmailDeliveryLogCountAggregateInputType | true
  }

export interface EmailDeliveryLogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EmailDeliveryLog'], meta: { name: 'EmailDeliveryLog' } }
  /**
   * Find zero or one EmailDeliveryLog that matches the filter.
   * @param {EmailDeliveryLogFindUniqueArgs} args - Arguments to find a EmailDeliveryLog
   * @example
   * // Get one EmailDeliveryLog
   * const emailDeliveryLog = await prisma.emailDeliveryLog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmailDeliveryLogFindUniqueArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EmailDeliveryLog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmailDeliveryLogFindUniqueOrThrowArgs} args - Arguments to find a EmailDeliveryLog
   * @example
   * // Get one EmailDeliveryLog
   * const emailDeliveryLog = await prisma.emailDeliveryLog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmailDeliveryLogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailDeliveryLog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailDeliveryLogFindFirstArgs} args - Arguments to find a EmailDeliveryLog
   * @example
   * // Get one EmailDeliveryLog
   * const emailDeliveryLog = await prisma.emailDeliveryLog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmailDeliveryLogFindFirstArgs>(args?: Prisma.SelectSubset<T, EmailDeliveryLogFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmailDeliveryLog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailDeliveryLogFindFirstOrThrowArgs} args - Arguments to find a EmailDeliveryLog
   * @example
   * // Get one EmailDeliveryLog
   * const emailDeliveryLog = await prisma.emailDeliveryLog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmailDeliveryLogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmailDeliveryLogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EmailDeliveryLogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailDeliveryLogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EmailDeliveryLogs
   * const emailDeliveryLogs = await prisma.emailDeliveryLog.findMany()
   * 
   * // Get first 10 EmailDeliveryLogs
   * const emailDeliveryLogs = await prisma.emailDeliveryLog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const emailDeliveryLogWithIdOnly = await prisma.emailDeliveryLog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmailDeliveryLogFindManyArgs>(args?: Prisma.SelectSubset<T, EmailDeliveryLogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EmailDeliveryLog.
   * @param {EmailDeliveryLogCreateArgs} args - Arguments to create a EmailDeliveryLog.
   * @example
   * // Create one EmailDeliveryLog
   * const EmailDeliveryLog = await prisma.emailDeliveryLog.create({
   *   data: {
   *     // ... data to create a EmailDeliveryLog
   *   }
   * })
   * 
   */
  create<T extends EmailDeliveryLogCreateArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogCreateArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EmailDeliveryLogs.
   * @param {EmailDeliveryLogCreateManyArgs} args - Arguments to create many EmailDeliveryLogs.
   * @example
   * // Create many EmailDeliveryLogs
   * const emailDeliveryLog = await prisma.emailDeliveryLog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmailDeliveryLogCreateManyArgs>(args?: Prisma.SelectSubset<T, EmailDeliveryLogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EmailDeliveryLogs and returns the data saved in the database.
   * @param {EmailDeliveryLogCreateManyAndReturnArgs} args - Arguments to create many EmailDeliveryLogs.
   * @example
   * // Create many EmailDeliveryLogs
   * const emailDeliveryLog = await prisma.emailDeliveryLog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EmailDeliveryLogs and only return the `id`
   * const emailDeliveryLogWithIdOnly = await prisma.emailDeliveryLog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmailDeliveryLogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmailDeliveryLogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EmailDeliveryLog.
   * @param {EmailDeliveryLogDeleteArgs} args - Arguments to delete one EmailDeliveryLog.
   * @example
   * // Delete one EmailDeliveryLog
   * const EmailDeliveryLog = await prisma.emailDeliveryLog.delete({
   *   where: {
   *     // ... filter to delete one EmailDeliveryLog
   *   }
   * })
   * 
   */
  delete<T extends EmailDeliveryLogDeleteArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogDeleteArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EmailDeliveryLog.
   * @param {EmailDeliveryLogUpdateArgs} args - Arguments to update one EmailDeliveryLog.
   * @example
   * // Update one EmailDeliveryLog
   * const emailDeliveryLog = await prisma.emailDeliveryLog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmailDeliveryLogUpdateArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogUpdateArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EmailDeliveryLogs.
   * @param {EmailDeliveryLogDeleteManyArgs} args - Arguments to filter EmailDeliveryLogs to delete.
   * @example
   * // Delete a few EmailDeliveryLogs
   * const { count } = await prisma.emailDeliveryLog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmailDeliveryLogDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmailDeliveryLogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmailDeliveryLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailDeliveryLogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EmailDeliveryLogs
   * const emailDeliveryLog = await prisma.emailDeliveryLog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmailDeliveryLogUpdateManyArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmailDeliveryLogs and returns the data updated in the database.
   * @param {EmailDeliveryLogUpdateManyAndReturnArgs} args - Arguments to update many EmailDeliveryLogs.
   * @example
   * // Update many EmailDeliveryLogs
   * const emailDeliveryLog = await prisma.emailDeliveryLog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EmailDeliveryLogs and only return the `id`
   * const emailDeliveryLogWithIdOnly = await prisma.emailDeliveryLog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmailDeliveryLogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EmailDeliveryLog.
   * @param {EmailDeliveryLogUpsertArgs} args - Arguments to update or create a EmailDeliveryLog.
   * @example
   * // Update or create a EmailDeliveryLog
   * const emailDeliveryLog = await prisma.emailDeliveryLog.upsert({
   *   create: {
   *     // ... data to create a EmailDeliveryLog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EmailDeliveryLog we want to update
   *   }
   * })
   */
  upsert<T extends EmailDeliveryLogUpsertArgs>(args: Prisma.SelectSubset<T, EmailDeliveryLogUpsertArgs<ExtArgs>>): Prisma.Prisma__EmailDeliveryLogClient<runtime.Types.Result.GetResult<Prisma.$EmailDeliveryLogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EmailDeliveryLogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailDeliveryLogCountArgs} args - Arguments to filter EmailDeliveryLogs to count.
   * @example
   * // Count the number of EmailDeliveryLogs
   * const count = await prisma.emailDeliveryLog.count({
   *   where: {
   *     // ... the filter for the EmailDeliveryLogs we want to count
   *   }
   * })
  **/
  count<T extends EmailDeliveryLogCountArgs>(
    args?: Prisma.Subset<T, EmailDeliveryLogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmailDeliveryLogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EmailDeliveryLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailDeliveryLogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmailDeliveryLogAggregateArgs>(args: Prisma.Subset<T, EmailDeliveryLogAggregateArgs>): Prisma.PrismaPromise<GetEmailDeliveryLogAggregateType<T>>

  /**
   * Group by EmailDeliveryLog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmailDeliveryLogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmailDeliveryLogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmailDeliveryLogGroupByArgs['orderBy'] }
      : { orderBy?: EmailDeliveryLogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmailDeliveryLogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmailDeliveryLogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EmailDeliveryLog model
 */
readonly fields: EmailDeliveryLogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EmailDeliveryLog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmailDeliveryLogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  invite<T extends Prisma.EmailDeliveryLog$inviteArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EmailDeliveryLog$inviteArgs<ExtArgs>>): Prisma.Prisma__OrganizationInviteClient<runtime.Types.Result.GetResult<Prisma.$OrganizationInvitePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EmailDeliveryLog model
 */
export interface EmailDeliveryLogFieldRefs {
  readonly id: Prisma.FieldRef<"EmailDeliveryLog", 'String'>
  readonly inviteId: Prisma.FieldRef<"EmailDeliveryLog", 'String'>
  readonly organizationId: Prisma.FieldRef<"EmailDeliveryLog", 'String'>
  readonly recipientEmail: Prisma.FieldRef<"EmailDeliveryLog", 'String'>
  readonly channel: Prisma.FieldRef<"EmailDeliveryLog", 'String'>
  readonly status: Prisma.FieldRef<"EmailDeliveryLog", 'DeliveryStatus'>
  readonly providerMessageId: Prisma.FieldRef<"EmailDeliveryLog", 'String'>
  readonly error: Prisma.FieldRef<"EmailDeliveryLog", 'String'>
  readonly metadata: Prisma.FieldRef<"EmailDeliveryLog", 'Json'>
  readonly createdAt: Prisma.FieldRef<"EmailDeliveryLog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * EmailDeliveryLog findUnique
 */
export type EmailDeliveryLogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailDeliveryLog to fetch.
   */
  where: Prisma.EmailDeliveryLogWhereUniqueInput
}

/**
 * EmailDeliveryLog findUniqueOrThrow
 */
export type EmailDeliveryLogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailDeliveryLog to fetch.
   */
  where: Prisma.EmailDeliveryLogWhereUniqueInput
}

/**
 * EmailDeliveryLog findFirst
 */
export type EmailDeliveryLogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailDeliveryLog to fetch.
   */
  where?: Prisma.EmailDeliveryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailDeliveryLogs to fetch.
   */
  orderBy?: Prisma.EmailDeliveryLogOrderByWithRelationInput | Prisma.EmailDeliveryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailDeliveryLogs.
   */
  cursor?: Prisma.EmailDeliveryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailDeliveryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailDeliveryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailDeliveryLogs.
   */
  distinct?: Prisma.EmailDeliveryLogScalarFieldEnum | Prisma.EmailDeliveryLogScalarFieldEnum[]
}

/**
 * EmailDeliveryLog findFirstOrThrow
 */
export type EmailDeliveryLogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailDeliveryLog to fetch.
   */
  where?: Prisma.EmailDeliveryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailDeliveryLogs to fetch.
   */
  orderBy?: Prisma.EmailDeliveryLogOrderByWithRelationInput | Prisma.EmailDeliveryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmailDeliveryLogs.
   */
  cursor?: Prisma.EmailDeliveryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailDeliveryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailDeliveryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailDeliveryLogs.
   */
  distinct?: Prisma.EmailDeliveryLogScalarFieldEnum | Prisma.EmailDeliveryLogScalarFieldEnum[]
}

/**
 * EmailDeliveryLog findMany
 */
export type EmailDeliveryLogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * Filter, which EmailDeliveryLogs to fetch.
   */
  where?: Prisma.EmailDeliveryLogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmailDeliveryLogs to fetch.
   */
  orderBy?: Prisma.EmailDeliveryLogOrderByWithRelationInput | Prisma.EmailDeliveryLogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EmailDeliveryLogs.
   */
  cursor?: Prisma.EmailDeliveryLogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmailDeliveryLogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmailDeliveryLogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmailDeliveryLogs.
   */
  distinct?: Prisma.EmailDeliveryLogScalarFieldEnum | Prisma.EmailDeliveryLogScalarFieldEnum[]
}

/**
 * EmailDeliveryLog create
 */
export type EmailDeliveryLogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * The data needed to create a EmailDeliveryLog.
   */
  data: Prisma.XOR<Prisma.EmailDeliveryLogCreateInput, Prisma.EmailDeliveryLogUncheckedCreateInput>
}

/**
 * EmailDeliveryLog createMany
 */
export type EmailDeliveryLogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EmailDeliveryLogs.
   */
  data: Prisma.EmailDeliveryLogCreateManyInput | Prisma.EmailDeliveryLogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * EmailDeliveryLog createManyAndReturn
 */
export type EmailDeliveryLogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * The data used to create many EmailDeliveryLogs.
   */
  data: Prisma.EmailDeliveryLogCreateManyInput | Prisma.EmailDeliveryLogCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EmailDeliveryLog update
 */
export type EmailDeliveryLogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * The data needed to update a EmailDeliveryLog.
   */
  data: Prisma.XOR<Prisma.EmailDeliveryLogUpdateInput, Prisma.EmailDeliveryLogUncheckedUpdateInput>
  /**
   * Choose, which EmailDeliveryLog to update.
   */
  where: Prisma.EmailDeliveryLogWhereUniqueInput
}

/**
 * EmailDeliveryLog updateMany
 */
export type EmailDeliveryLogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EmailDeliveryLogs.
   */
  data: Prisma.XOR<Prisma.EmailDeliveryLogUpdateManyMutationInput, Prisma.EmailDeliveryLogUncheckedUpdateManyInput>
  /**
   * Filter which EmailDeliveryLogs to update
   */
  where?: Prisma.EmailDeliveryLogWhereInput
  /**
   * Limit how many EmailDeliveryLogs to update.
   */
  limit?: number
}

/**
 * EmailDeliveryLog updateManyAndReturn
 */
export type EmailDeliveryLogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * The data used to update EmailDeliveryLogs.
   */
  data: Prisma.XOR<Prisma.EmailDeliveryLogUpdateManyMutationInput, Prisma.EmailDeliveryLogUncheckedUpdateManyInput>
  /**
   * Filter which EmailDeliveryLogs to update
   */
  where?: Prisma.EmailDeliveryLogWhereInput
  /**
   * Limit how many EmailDeliveryLogs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EmailDeliveryLog upsert
 */
export type EmailDeliveryLogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * The filter to search for the EmailDeliveryLog to update in case it exists.
   */
  where: Prisma.EmailDeliveryLogWhereUniqueInput
  /**
   * In case the EmailDeliveryLog found by the `where` argument doesn't exist, create a new EmailDeliveryLog with this data.
   */
  create: Prisma.XOR<Prisma.EmailDeliveryLogCreateInput, Prisma.EmailDeliveryLogUncheckedCreateInput>
  /**
   * In case the EmailDeliveryLog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmailDeliveryLogUpdateInput, Prisma.EmailDeliveryLogUncheckedUpdateInput>
}

/**
 * EmailDeliveryLog delete
 */
export type EmailDeliveryLogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
  /**
   * Filter which EmailDeliveryLog to delete.
   */
  where: Prisma.EmailDeliveryLogWhereUniqueInput
}

/**
 * EmailDeliveryLog deleteMany
 */
export type EmailDeliveryLogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmailDeliveryLogs to delete
   */
  where?: Prisma.EmailDeliveryLogWhereInput
  /**
   * Limit how many EmailDeliveryLogs to delete.
   */
  limit?: number
}

/**
 * EmailDeliveryLog.invite
 */
export type EmailDeliveryLog$inviteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationInvite
   */
  select?: Prisma.OrganizationInviteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationInvite
   */
  omit?: Prisma.OrganizationInviteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInviteInclude<ExtArgs> | null
  where?: Prisma.OrganizationInviteWhereInput
}

/**
 * EmailDeliveryLog without action
 */
export type EmailDeliveryLogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmailDeliveryLog
   */
  select?: Prisma.EmailDeliveryLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmailDeliveryLog
   */
  omit?: Prisma.EmailDeliveryLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmailDeliveryLogInclude<ExtArgs> | null
}
