
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrganizationDepartment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OrganizationDepartment
 * 
 */
export type OrganizationDepartmentModel = runtime.Types.Result.DefaultSelection<Prisma.$OrganizationDepartmentPayload>

export type AggregateOrganizationDepartment = {
  _count: OrganizationDepartmentCountAggregateOutputType | null
  _min: OrganizationDepartmentMinAggregateOutputType | null
  _max: OrganizationDepartmentMaxAggregateOutputType | null
}

export type OrganizationDepartmentMinAggregateOutputType = {
  id: string | null
  organizationId: string | null
  name: string | null
  nameNormalized: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrganizationDepartmentMaxAggregateOutputType = {
  id: string | null
  organizationId: string | null
  name: string | null
  nameNormalized: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrganizationDepartmentCountAggregateOutputType = {
  id: number
  organizationId: number
  name: number
  nameNormalized: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OrganizationDepartmentMinAggregateInputType = {
  id?: true
  organizationId?: true
  name?: true
  nameNormalized?: true
  createdAt?: true
  updatedAt?: true
}

export type OrganizationDepartmentMaxAggregateInputType = {
  id?: true
  organizationId?: true
  name?: true
  nameNormalized?: true
  createdAt?: true
  updatedAt?: true
}

export type OrganizationDepartmentCountAggregateInputType = {
  id?: true
  organizationId?: true
  name?: true
  nameNormalized?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OrganizationDepartmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrganizationDepartment to aggregate.
   */
  where?: Prisma.OrganizationDepartmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrganizationDepartments to fetch.
   */
  orderBy?: Prisma.OrganizationDepartmentOrderByWithRelationInput | Prisma.OrganizationDepartmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrganizationDepartmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrganizationDepartments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrganizationDepartments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrganizationDepartments
  **/
  _count?: true | OrganizationDepartmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrganizationDepartmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrganizationDepartmentMaxAggregateInputType
}

export type GetOrganizationDepartmentAggregateType<T extends OrganizationDepartmentAggregateArgs> = {
      [P in keyof T & keyof AggregateOrganizationDepartment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrganizationDepartment[P]>
    : Prisma.GetScalarType<T[P], AggregateOrganizationDepartment[P]>
}




export type OrganizationDepartmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrganizationDepartmentWhereInput
  orderBy?: Prisma.OrganizationDepartmentOrderByWithAggregationInput | Prisma.OrganizationDepartmentOrderByWithAggregationInput[]
  by: Prisma.OrganizationDepartmentScalarFieldEnum[] | Prisma.OrganizationDepartmentScalarFieldEnum
  having?: Prisma.OrganizationDepartmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrganizationDepartmentCountAggregateInputType | true
  _min?: OrganizationDepartmentMinAggregateInputType
  _max?: OrganizationDepartmentMaxAggregateInputType
}

export type OrganizationDepartmentGroupByOutputType = {
  id: string
  organizationId: string
  name: string
  nameNormalized: string
  createdAt: Date
  updatedAt: Date
  _count: OrganizationDepartmentCountAggregateOutputType | null
  _min: OrganizationDepartmentMinAggregateOutputType | null
  _max: OrganizationDepartmentMaxAggregateOutputType | null
}

type GetOrganizationDepartmentGroupByPayload<T extends OrganizationDepartmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrganizationDepartmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrganizationDepartmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrganizationDepartmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrganizationDepartmentGroupByOutputType[P]>
      }
    >
  >



export type OrganizationDepartmentWhereInput = {
  AND?: Prisma.OrganizationDepartmentWhereInput | Prisma.OrganizationDepartmentWhereInput[]
  OR?: Prisma.OrganizationDepartmentWhereInput[]
  NOT?: Prisma.OrganizationDepartmentWhereInput | Prisma.OrganizationDepartmentWhereInput[]
  id?: Prisma.StringFilter<"OrganizationDepartment"> | string
  organizationId?: Prisma.StringFilter<"OrganizationDepartment"> | string
  name?: Prisma.StringFilter<"OrganizationDepartment"> | string
  nameNormalized?: Prisma.StringFilter<"OrganizationDepartment"> | string
  createdAt?: Prisma.DateTimeFilter<"OrganizationDepartment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrganizationDepartment"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  members?: Prisma.OrganizationMemberListRelationFilter
  scans?: Prisma.ScanListRelationFilter
}

export type OrganizationDepartmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameNormalized?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  organization?: Prisma.OrganizationOrderByWithRelationInput
  members?: Prisma.OrganizationMemberOrderByRelationAggregateInput
  scans?: Prisma.ScanOrderByRelationAggregateInput
}

export type OrganizationDepartmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  organizationId_nameNormalized?: Prisma.OrganizationDepartmentOrganizationIdNameNormalizedCompoundUniqueInput
  AND?: Prisma.OrganizationDepartmentWhereInput | Prisma.OrganizationDepartmentWhereInput[]
  OR?: Prisma.OrganizationDepartmentWhereInput[]
  NOT?: Prisma.OrganizationDepartmentWhereInput | Prisma.OrganizationDepartmentWhereInput[]
  organizationId?: Prisma.StringFilter<"OrganizationDepartment"> | string
  name?: Prisma.StringFilter<"OrganizationDepartment"> | string
  nameNormalized?: Prisma.StringFilter<"OrganizationDepartment"> | string
  createdAt?: Prisma.DateTimeFilter<"OrganizationDepartment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrganizationDepartment"> | Date | string
  organization?: Prisma.XOR<Prisma.OrganizationScalarRelationFilter, Prisma.OrganizationWhereInput>
  members?: Prisma.OrganizationMemberListRelationFilter
  scans?: Prisma.ScanListRelationFilter
}, "id" | "organizationId_nameNormalized">

export type OrganizationDepartmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameNormalized?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OrganizationDepartmentCountOrderByAggregateInput
  _max?: Prisma.OrganizationDepartmentMaxOrderByAggregateInput
  _min?: Prisma.OrganizationDepartmentMinOrderByAggregateInput
}

export type OrganizationDepartmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrganizationDepartmentScalarWhereWithAggregatesInput | Prisma.OrganizationDepartmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrganizationDepartmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrganizationDepartmentScalarWhereWithAggregatesInput | Prisma.OrganizationDepartmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OrganizationDepartment"> | string
  organizationId?: Prisma.StringWithAggregatesFilter<"OrganizationDepartment"> | string
  name?: Prisma.StringWithAggregatesFilter<"OrganizationDepartment"> | string
  nameNormalized?: Prisma.StringWithAggregatesFilter<"OrganizationDepartment"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OrganizationDepartment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OrganizationDepartment"> | Date | string
}

export type OrganizationDepartmentCreateInput = {
  id?: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutOrganizationDepartmentsInput
  members?: Prisma.OrganizationMemberCreateNestedManyWithoutDepartmentInput
  scans?: Prisma.ScanCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentUncheckedCreateInput = {
  id?: string
  organizationId: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  members?: Prisma.OrganizationMemberUncheckedCreateNestedManyWithoutDepartmentInput
  scans?: Prisma.ScanUncheckedCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutOrganizationDepartmentsNestedInput
  members?: Prisma.OrganizationMemberUpdateManyWithoutDepartmentNestedInput
  scans?: Prisma.ScanUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUncheckedUpdateManyWithoutDepartmentNestedInput
  scans?: Prisma.ScanUncheckedUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentCreateManyInput = {
  id?: string
  organizationId: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrganizationDepartmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrganizationDepartmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrganizationDepartmentListRelationFilter = {
  every?: Prisma.OrganizationDepartmentWhereInput
  some?: Prisma.OrganizationDepartmentWhereInput
  none?: Prisma.OrganizationDepartmentWhereInput
}

export type OrganizationDepartmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrganizationDepartmentNullableScalarRelationFilter = {
  is?: Prisma.OrganizationDepartmentWhereInput | null
  isNot?: Prisma.OrganizationDepartmentWhereInput | null
}

export type OrganizationDepartmentOrganizationIdNameNormalizedCompoundUniqueInput = {
  organizationId: string
  nameNormalized: string
}

export type OrganizationDepartmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameNormalized?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrganizationDepartmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameNormalized?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrganizationDepartmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  organizationId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  nameNormalized?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrganizationDepartmentCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput> | Prisma.OrganizationDepartmentCreateWithoutOrganizationInput[] | Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput | Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.OrganizationDepartmentCreateManyOrganizationInputEnvelope
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
}

export type OrganizationDepartmentUncheckedCreateNestedManyWithoutOrganizationInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput> | Prisma.OrganizationDepartmentCreateWithoutOrganizationInput[] | Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput | Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput[]
  createMany?: Prisma.OrganizationDepartmentCreateManyOrganizationInputEnvelope
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
}

export type OrganizationDepartmentUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput> | Prisma.OrganizationDepartmentCreateWithoutOrganizationInput[] | Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput | Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.OrganizationDepartmentUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.OrganizationDepartmentUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.OrganizationDepartmentCreateManyOrganizationInputEnvelope
  set?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  disconnect?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  delete?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  update?: Prisma.OrganizationDepartmentUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.OrganizationDepartmentUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.OrganizationDepartmentUpdateManyWithWhereWithoutOrganizationInput | Prisma.OrganizationDepartmentUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.OrganizationDepartmentScalarWhereInput | Prisma.OrganizationDepartmentScalarWhereInput[]
}

export type OrganizationDepartmentUncheckedUpdateManyWithoutOrganizationNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput> | Prisma.OrganizationDepartmentCreateWithoutOrganizationInput[] | Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput[]
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput | Prisma.OrganizationDepartmentCreateOrConnectWithoutOrganizationInput[]
  upsert?: Prisma.OrganizationDepartmentUpsertWithWhereUniqueWithoutOrganizationInput | Prisma.OrganizationDepartmentUpsertWithWhereUniqueWithoutOrganizationInput[]
  createMany?: Prisma.OrganizationDepartmentCreateManyOrganizationInputEnvelope
  set?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  disconnect?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  delete?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput | Prisma.OrganizationDepartmentWhereUniqueInput[]
  update?: Prisma.OrganizationDepartmentUpdateWithWhereUniqueWithoutOrganizationInput | Prisma.OrganizationDepartmentUpdateWithWhereUniqueWithoutOrganizationInput[]
  updateMany?: Prisma.OrganizationDepartmentUpdateManyWithWhereWithoutOrganizationInput | Prisma.OrganizationDepartmentUpdateManyWithWhereWithoutOrganizationInput[]
  deleteMany?: Prisma.OrganizationDepartmentScalarWhereInput | Prisma.OrganizationDepartmentScalarWhereInput[]
}

export type OrganizationDepartmentCreateNestedOneWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutMembersInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutMembersInput
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput
}

export type OrganizationDepartmentUpdateOneWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutMembersInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutMembersInput
  upsert?: Prisma.OrganizationDepartmentUpsertWithoutMembersInput
  disconnect?: Prisma.OrganizationDepartmentWhereInput | boolean
  delete?: Prisma.OrganizationDepartmentWhereInput | boolean
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrganizationDepartmentUpdateToOneWithWhereWithoutMembersInput, Prisma.OrganizationDepartmentUpdateWithoutMembersInput>, Prisma.OrganizationDepartmentUncheckedUpdateWithoutMembersInput>
}

export type OrganizationDepartmentCreateNestedOneWithoutScansInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutScansInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutScansInput>
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutScansInput
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput
}

export type OrganizationDepartmentUpdateOneWithoutScansNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutScansInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutScansInput>
  connectOrCreate?: Prisma.OrganizationDepartmentCreateOrConnectWithoutScansInput
  upsert?: Prisma.OrganizationDepartmentUpsertWithoutScansInput
  disconnect?: Prisma.OrganizationDepartmentWhereInput | boolean
  delete?: Prisma.OrganizationDepartmentWhereInput | boolean
  connect?: Prisma.OrganizationDepartmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrganizationDepartmentUpdateToOneWithWhereWithoutScansInput, Prisma.OrganizationDepartmentUpdateWithoutScansInput>, Prisma.OrganizationDepartmentUncheckedUpdateWithoutScansInput>
}

export type OrganizationDepartmentCreateWithoutOrganizationInput = {
  id?: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  members?: Prisma.OrganizationMemberCreateNestedManyWithoutDepartmentInput
  scans?: Prisma.ScanCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentUncheckedCreateWithoutOrganizationInput = {
  id?: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  members?: Prisma.OrganizationMemberUncheckedCreateNestedManyWithoutDepartmentInput
  scans?: Prisma.ScanUncheckedCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentCreateOrConnectWithoutOrganizationInput = {
  where: Prisma.OrganizationDepartmentWhereUniqueInput
  create: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput>
}

export type OrganizationDepartmentCreateManyOrganizationInputEnvelope = {
  data: Prisma.OrganizationDepartmentCreateManyOrganizationInput | Prisma.OrganizationDepartmentCreateManyOrganizationInput[]
  skipDuplicates?: boolean
}

export type OrganizationDepartmentUpsertWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.OrganizationDepartmentWhereUniqueInput
  update: Prisma.XOR<Prisma.OrganizationDepartmentUpdateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedUpdateWithoutOrganizationInput>
  create: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutOrganizationInput>
}

export type OrganizationDepartmentUpdateWithWhereUniqueWithoutOrganizationInput = {
  where: Prisma.OrganizationDepartmentWhereUniqueInput
  data: Prisma.XOR<Prisma.OrganizationDepartmentUpdateWithoutOrganizationInput, Prisma.OrganizationDepartmentUncheckedUpdateWithoutOrganizationInput>
}

export type OrganizationDepartmentUpdateManyWithWhereWithoutOrganizationInput = {
  where: Prisma.OrganizationDepartmentScalarWhereInput
  data: Prisma.XOR<Prisma.OrganizationDepartmentUpdateManyMutationInput, Prisma.OrganizationDepartmentUncheckedUpdateManyWithoutOrganizationInput>
}

export type OrganizationDepartmentScalarWhereInput = {
  AND?: Prisma.OrganizationDepartmentScalarWhereInput | Prisma.OrganizationDepartmentScalarWhereInput[]
  OR?: Prisma.OrganizationDepartmentScalarWhereInput[]
  NOT?: Prisma.OrganizationDepartmentScalarWhereInput | Prisma.OrganizationDepartmentScalarWhereInput[]
  id?: Prisma.StringFilter<"OrganizationDepartment"> | string
  organizationId?: Prisma.StringFilter<"OrganizationDepartment"> | string
  name?: Prisma.StringFilter<"OrganizationDepartment"> | string
  nameNormalized?: Prisma.StringFilter<"OrganizationDepartment"> | string
  createdAt?: Prisma.DateTimeFilter<"OrganizationDepartment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrganizationDepartment"> | Date | string
}

export type OrganizationDepartmentCreateWithoutMembersInput = {
  id?: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutOrganizationDepartmentsInput
  scans?: Prisma.ScanCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentUncheckedCreateWithoutMembersInput = {
  id?: string
  organizationId: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  scans?: Prisma.ScanUncheckedCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentCreateOrConnectWithoutMembersInput = {
  where: Prisma.OrganizationDepartmentWhereUniqueInput
  create: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutMembersInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutMembersInput>
}

export type OrganizationDepartmentUpsertWithoutMembersInput = {
  update: Prisma.XOR<Prisma.OrganizationDepartmentUpdateWithoutMembersInput, Prisma.OrganizationDepartmentUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutMembersInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutMembersInput>
  where?: Prisma.OrganizationDepartmentWhereInput
}

export type OrganizationDepartmentUpdateToOneWithWhereWithoutMembersInput = {
  where?: Prisma.OrganizationDepartmentWhereInput
  data: Prisma.XOR<Prisma.OrganizationDepartmentUpdateWithoutMembersInput, Prisma.OrganizationDepartmentUncheckedUpdateWithoutMembersInput>
}

export type OrganizationDepartmentUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutOrganizationDepartmentsNestedInput
  scans?: Prisma.ScanUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scans?: Prisma.ScanUncheckedUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentCreateWithoutScansInput = {
  id?: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  organization: Prisma.OrganizationCreateNestedOneWithoutOrganizationDepartmentsInput
  members?: Prisma.OrganizationMemberCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentUncheckedCreateWithoutScansInput = {
  id?: string
  organizationId: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
  members?: Prisma.OrganizationMemberUncheckedCreateNestedManyWithoutDepartmentInput
}

export type OrganizationDepartmentCreateOrConnectWithoutScansInput = {
  where: Prisma.OrganizationDepartmentWhereUniqueInput
  create: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutScansInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutScansInput>
}

export type OrganizationDepartmentUpsertWithoutScansInput = {
  update: Prisma.XOR<Prisma.OrganizationDepartmentUpdateWithoutScansInput, Prisma.OrganizationDepartmentUncheckedUpdateWithoutScansInput>
  create: Prisma.XOR<Prisma.OrganizationDepartmentCreateWithoutScansInput, Prisma.OrganizationDepartmentUncheckedCreateWithoutScansInput>
  where?: Prisma.OrganizationDepartmentWhereInput
}

export type OrganizationDepartmentUpdateToOneWithWhereWithoutScansInput = {
  where?: Prisma.OrganizationDepartmentWhereInput
  data: Prisma.XOR<Prisma.OrganizationDepartmentUpdateWithoutScansInput, Prisma.OrganizationDepartmentUncheckedUpdateWithoutScansInput>
}

export type OrganizationDepartmentUpdateWithoutScansInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  organization?: Prisma.OrganizationUpdateOneRequiredWithoutOrganizationDepartmentsNestedInput
  members?: Prisma.OrganizationMemberUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentUncheckedUpdateWithoutScansInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  organizationId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUncheckedUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentCreateManyOrganizationInput = {
  id?: string
  name: string
  nameNormalized: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrganizationDepartmentUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUpdateManyWithoutDepartmentNestedInput
  scans?: Prisma.ScanUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentUncheckedUpdateWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUncheckedUpdateManyWithoutDepartmentNestedInput
  scans?: Prisma.ScanUncheckedUpdateManyWithoutDepartmentNestedInput
}

export type OrganizationDepartmentUncheckedUpdateManyWithoutOrganizationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  nameNormalized?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type OrganizationDepartmentCountOutputType
 */

export type OrganizationDepartmentCountOutputType = {
  members: number
  scans: number
}

export type OrganizationDepartmentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | OrganizationDepartmentCountOutputTypeCountMembersArgs
  scans?: boolean | OrganizationDepartmentCountOutputTypeCountScansArgs
}

/**
 * OrganizationDepartmentCountOutputType without action
 */
export type OrganizationDepartmentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartmentCountOutputType
   */
  select?: Prisma.OrganizationDepartmentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OrganizationDepartmentCountOutputType without action
 */
export type OrganizationDepartmentCountOutputTypeCountMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrganizationMemberWhereInput
}

/**
 * OrganizationDepartmentCountOutputType without action
 */
export type OrganizationDepartmentCountOutputTypeCountScansArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ScanWhereInput
}


export type OrganizationDepartmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  name?: boolean
  nameNormalized?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  members?: boolean | Prisma.OrganizationDepartment$membersArgs<ExtArgs>
  scans?: boolean | Prisma.OrganizationDepartment$scansArgs<ExtArgs>
  _count?: boolean | Prisma.OrganizationDepartmentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["organizationDepartment"]>

export type OrganizationDepartmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  name?: boolean
  nameNormalized?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["organizationDepartment"]>

export type OrganizationDepartmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  organizationId?: boolean
  name?: boolean
  nameNormalized?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}, ExtArgs["result"]["organizationDepartment"]>

export type OrganizationDepartmentSelectScalar = {
  id?: boolean
  organizationId?: boolean
  name?: boolean
  nameNormalized?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OrganizationDepartmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "organizationId" | "name" | "nameNormalized" | "createdAt" | "updatedAt", ExtArgs["result"]["organizationDepartment"]>
export type OrganizationDepartmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
  members?: boolean | Prisma.OrganizationDepartment$membersArgs<ExtArgs>
  scans?: boolean | Prisma.OrganizationDepartment$scansArgs<ExtArgs>
  _count?: boolean | Prisma.OrganizationDepartmentCountOutputTypeDefaultArgs<ExtArgs>
}
export type OrganizationDepartmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}
export type OrganizationDepartmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  organization?: boolean | Prisma.OrganizationDefaultArgs<ExtArgs>
}

export type $OrganizationDepartmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrganizationDepartment"
  objects: {
    organization: Prisma.$OrganizationPayload<ExtArgs>
    members: Prisma.$OrganizationMemberPayload<ExtArgs>[]
    scans: Prisma.$ScanPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    organizationId: string
    name: string
    nameNormalized: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["organizationDepartment"]>
  composites: {}
}

export type OrganizationDepartmentGetPayload<S extends boolean | null | undefined | OrganizationDepartmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload, S>

export type OrganizationDepartmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrganizationDepartmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrganizationDepartmentCountAggregateInputType | true
  }

export interface OrganizationDepartmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrganizationDepartment'], meta: { name: 'OrganizationDepartment' } }
  /**
   * Find zero or one OrganizationDepartment that matches the filter.
   * @param {OrganizationDepartmentFindUniqueArgs} args - Arguments to find a OrganizationDepartment
   * @example
   * // Get one OrganizationDepartment
   * const organizationDepartment = await prisma.organizationDepartment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrganizationDepartmentFindUniqueArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrganizationDepartment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrganizationDepartmentFindUniqueOrThrowArgs} args - Arguments to find a OrganizationDepartment
   * @example
   * // Get one OrganizationDepartment
   * const organizationDepartment = await prisma.organizationDepartment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrganizationDepartmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrganizationDepartment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationDepartmentFindFirstArgs} args - Arguments to find a OrganizationDepartment
   * @example
   * // Get one OrganizationDepartment
   * const organizationDepartment = await prisma.organizationDepartment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrganizationDepartmentFindFirstArgs>(args?: Prisma.SelectSubset<T, OrganizationDepartmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrganizationDepartment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationDepartmentFindFirstOrThrowArgs} args - Arguments to find a OrganizationDepartment
   * @example
   * // Get one OrganizationDepartment
   * const organizationDepartment = await prisma.organizationDepartment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrganizationDepartmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrganizationDepartmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrganizationDepartments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationDepartmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrganizationDepartments
   * const organizationDepartments = await prisma.organizationDepartment.findMany()
   * 
   * // Get first 10 OrganizationDepartments
   * const organizationDepartments = await prisma.organizationDepartment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const organizationDepartmentWithIdOnly = await prisma.organizationDepartment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrganizationDepartmentFindManyArgs>(args?: Prisma.SelectSubset<T, OrganizationDepartmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrganizationDepartment.
   * @param {OrganizationDepartmentCreateArgs} args - Arguments to create a OrganizationDepartment.
   * @example
   * // Create one OrganizationDepartment
   * const OrganizationDepartment = await prisma.organizationDepartment.create({
   *   data: {
   *     // ... data to create a OrganizationDepartment
   *   }
   * })
   * 
   */
  create<T extends OrganizationDepartmentCreateArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentCreateArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrganizationDepartments.
   * @param {OrganizationDepartmentCreateManyArgs} args - Arguments to create many OrganizationDepartments.
   * @example
   * // Create many OrganizationDepartments
   * const organizationDepartment = await prisma.organizationDepartment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrganizationDepartmentCreateManyArgs>(args?: Prisma.SelectSubset<T, OrganizationDepartmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrganizationDepartments and returns the data saved in the database.
   * @param {OrganizationDepartmentCreateManyAndReturnArgs} args - Arguments to create many OrganizationDepartments.
   * @example
   * // Create many OrganizationDepartments
   * const organizationDepartment = await prisma.organizationDepartment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrganizationDepartments and only return the `id`
   * const organizationDepartmentWithIdOnly = await prisma.organizationDepartment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrganizationDepartmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrganizationDepartmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrganizationDepartment.
   * @param {OrganizationDepartmentDeleteArgs} args - Arguments to delete one OrganizationDepartment.
   * @example
   * // Delete one OrganizationDepartment
   * const OrganizationDepartment = await prisma.organizationDepartment.delete({
   *   where: {
   *     // ... filter to delete one OrganizationDepartment
   *   }
   * })
   * 
   */
  delete<T extends OrganizationDepartmentDeleteArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentDeleteArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrganizationDepartment.
   * @param {OrganizationDepartmentUpdateArgs} args - Arguments to update one OrganizationDepartment.
   * @example
   * // Update one OrganizationDepartment
   * const organizationDepartment = await prisma.organizationDepartment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrganizationDepartmentUpdateArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentUpdateArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrganizationDepartments.
   * @param {OrganizationDepartmentDeleteManyArgs} args - Arguments to filter OrganizationDepartments to delete.
   * @example
   * // Delete a few OrganizationDepartments
   * const { count } = await prisma.organizationDepartment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrganizationDepartmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrganizationDepartmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrganizationDepartments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationDepartmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrganizationDepartments
   * const organizationDepartment = await prisma.organizationDepartment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrganizationDepartmentUpdateManyArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrganizationDepartments and returns the data updated in the database.
   * @param {OrganizationDepartmentUpdateManyAndReturnArgs} args - Arguments to update many OrganizationDepartments.
   * @example
   * // Update many OrganizationDepartments
   * const organizationDepartment = await prisma.organizationDepartment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrganizationDepartments and only return the `id`
   * const organizationDepartmentWithIdOnly = await prisma.organizationDepartment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrganizationDepartmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrganizationDepartment.
   * @param {OrganizationDepartmentUpsertArgs} args - Arguments to update or create a OrganizationDepartment.
   * @example
   * // Update or create a OrganizationDepartment
   * const organizationDepartment = await prisma.organizationDepartment.upsert({
   *   create: {
   *     // ... data to create a OrganizationDepartment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrganizationDepartment we want to update
   *   }
   * })
   */
  upsert<T extends OrganizationDepartmentUpsertArgs>(args: Prisma.SelectSubset<T, OrganizationDepartmentUpsertArgs<ExtArgs>>): Prisma.Prisma__OrganizationDepartmentClient<runtime.Types.Result.GetResult<Prisma.$OrganizationDepartmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrganizationDepartments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationDepartmentCountArgs} args - Arguments to filter OrganizationDepartments to count.
   * @example
   * // Count the number of OrganizationDepartments
   * const count = await prisma.organizationDepartment.count({
   *   where: {
   *     // ... the filter for the OrganizationDepartments we want to count
   *   }
   * })
  **/
  count<T extends OrganizationDepartmentCountArgs>(
    args?: Prisma.Subset<T, OrganizationDepartmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrganizationDepartmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrganizationDepartment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationDepartmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrganizationDepartmentAggregateArgs>(args: Prisma.Subset<T, OrganizationDepartmentAggregateArgs>): Prisma.PrismaPromise<GetOrganizationDepartmentAggregateType<T>>

  /**
   * Group by OrganizationDepartment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationDepartmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrganizationDepartmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrganizationDepartmentGroupByArgs['orderBy'] }
      : { orderBy?: OrganizationDepartmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrganizationDepartmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrganizationDepartmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrganizationDepartment model
 */
readonly fields: OrganizationDepartmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrganizationDepartment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrganizationDepartmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  organization<T extends Prisma.OrganizationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDefaultArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  members<T extends Prisma.OrganizationDepartment$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDepartment$membersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  scans<T extends Prisma.OrganizationDepartment$scansArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrganizationDepartment$scansArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ScanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrganizationDepartment model
 */
export interface OrganizationDepartmentFieldRefs {
  readonly id: Prisma.FieldRef<"OrganizationDepartment", 'String'>
  readonly organizationId: Prisma.FieldRef<"OrganizationDepartment", 'String'>
  readonly name: Prisma.FieldRef<"OrganizationDepartment", 'String'>
  readonly nameNormalized: Prisma.FieldRef<"OrganizationDepartment", 'String'>
  readonly createdAt: Prisma.FieldRef<"OrganizationDepartment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OrganizationDepartment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OrganizationDepartment findUnique
 */
export type OrganizationDepartmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * Filter, which OrganizationDepartment to fetch.
   */
  where: Prisma.OrganizationDepartmentWhereUniqueInput
}

/**
 * OrganizationDepartment findUniqueOrThrow
 */
export type OrganizationDepartmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * Filter, which OrganizationDepartment to fetch.
   */
  where: Prisma.OrganizationDepartmentWhereUniqueInput
}

/**
 * OrganizationDepartment findFirst
 */
export type OrganizationDepartmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * Filter, which OrganizationDepartment to fetch.
   */
  where?: Prisma.OrganizationDepartmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrganizationDepartments to fetch.
   */
  orderBy?: Prisma.OrganizationDepartmentOrderByWithRelationInput | Prisma.OrganizationDepartmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrganizationDepartments.
   */
  cursor?: Prisma.OrganizationDepartmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrganizationDepartments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrganizationDepartments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrganizationDepartments.
   */
  distinct?: Prisma.OrganizationDepartmentScalarFieldEnum | Prisma.OrganizationDepartmentScalarFieldEnum[]
}

/**
 * OrganizationDepartment findFirstOrThrow
 */
export type OrganizationDepartmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * Filter, which OrganizationDepartment to fetch.
   */
  where?: Prisma.OrganizationDepartmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrganizationDepartments to fetch.
   */
  orderBy?: Prisma.OrganizationDepartmentOrderByWithRelationInput | Prisma.OrganizationDepartmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrganizationDepartments.
   */
  cursor?: Prisma.OrganizationDepartmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrganizationDepartments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrganizationDepartments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrganizationDepartments.
   */
  distinct?: Prisma.OrganizationDepartmentScalarFieldEnum | Prisma.OrganizationDepartmentScalarFieldEnum[]
}

/**
 * OrganizationDepartment findMany
 */
export type OrganizationDepartmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * Filter, which OrganizationDepartments to fetch.
   */
  where?: Prisma.OrganizationDepartmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrganizationDepartments to fetch.
   */
  orderBy?: Prisma.OrganizationDepartmentOrderByWithRelationInput | Prisma.OrganizationDepartmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrganizationDepartments.
   */
  cursor?: Prisma.OrganizationDepartmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrganizationDepartments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrganizationDepartments.
   */
  skip?: number
  distinct?: Prisma.OrganizationDepartmentScalarFieldEnum | Prisma.OrganizationDepartmentScalarFieldEnum[]
}

/**
 * OrganizationDepartment create
 */
export type OrganizationDepartmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * The data needed to create a OrganizationDepartment.
   */
  data: Prisma.XOR<Prisma.OrganizationDepartmentCreateInput, Prisma.OrganizationDepartmentUncheckedCreateInput>
}

/**
 * OrganizationDepartment createMany
 */
export type OrganizationDepartmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrganizationDepartments.
   */
  data: Prisma.OrganizationDepartmentCreateManyInput | Prisma.OrganizationDepartmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrganizationDepartment createManyAndReturn
 */
export type OrganizationDepartmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * The data used to create many OrganizationDepartments.
   */
  data: Prisma.OrganizationDepartmentCreateManyInput | Prisma.OrganizationDepartmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OrganizationDepartment update
 */
export type OrganizationDepartmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * The data needed to update a OrganizationDepartment.
   */
  data: Prisma.XOR<Prisma.OrganizationDepartmentUpdateInput, Prisma.OrganizationDepartmentUncheckedUpdateInput>
  /**
   * Choose, which OrganizationDepartment to update.
   */
  where: Prisma.OrganizationDepartmentWhereUniqueInput
}

/**
 * OrganizationDepartment updateMany
 */
export type OrganizationDepartmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrganizationDepartments.
   */
  data: Prisma.XOR<Prisma.OrganizationDepartmentUpdateManyMutationInput, Prisma.OrganizationDepartmentUncheckedUpdateManyInput>
  /**
   * Filter which OrganizationDepartments to update
   */
  where?: Prisma.OrganizationDepartmentWhereInput
  /**
   * Limit how many OrganizationDepartments to update.
   */
  limit?: number
}

/**
 * OrganizationDepartment updateManyAndReturn
 */
export type OrganizationDepartmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * The data used to update OrganizationDepartments.
   */
  data: Prisma.XOR<Prisma.OrganizationDepartmentUpdateManyMutationInput, Prisma.OrganizationDepartmentUncheckedUpdateManyInput>
  /**
   * Filter which OrganizationDepartments to update
   */
  where?: Prisma.OrganizationDepartmentWhereInput
  /**
   * Limit how many OrganizationDepartments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OrganizationDepartment upsert
 */
export type OrganizationDepartmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * The filter to search for the OrganizationDepartment to update in case it exists.
   */
  where: Prisma.OrganizationDepartmentWhereUniqueInput
  /**
   * In case the OrganizationDepartment found by the `where` argument doesn't exist, create a new OrganizationDepartment with this data.
   */
  create: Prisma.XOR<Prisma.OrganizationDepartmentCreateInput, Prisma.OrganizationDepartmentUncheckedCreateInput>
  /**
   * In case the OrganizationDepartment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrganizationDepartmentUpdateInput, Prisma.OrganizationDepartmentUncheckedUpdateInput>
}

/**
 * OrganizationDepartment delete
 */
export type OrganizationDepartmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
  /**
   * Filter which OrganizationDepartment to delete.
   */
  where: Prisma.OrganizationDepartmentWhereUniqueInput
}

/**
 * OrganizationDepartment deleteMany
 */
export type OrganizationDepartmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrganizationDepartments to delete
   */
  where?: Prisma.OrganizationDepartmentWhereInput
  /**
   * Limit how many OrganizationDepartments to delete.
   */
  limit?: number
}

/**
 * OrganizationDepartment.members
 */
export type OrganizationDepartment$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationMember
   */
  select?: Prisma.OrganizationMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationMember
   */
  omit?: Prisma.OrganizationMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationMemberInclude<ExtArgs> | null
  where?: Prisma.OrganizationMemberWhereInput
  orderBy?: Prisma.OrganizationMemberOrderByWithRelationInput | Prisma.OrganizationMemberOrderByWithRelationInput[]
  cursor?: Prisma.OrganizationMemberWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrganizationMemberScalarFieldEnum | Prisma.OrganizationMemberScalarFieldEnum[]
}

/**
 * OrganizationDepartment.scans
 */
export type OrganizationDepartment$scansArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Scan
   */
  select?: Prisma.ScanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Scan
   */
  omit?: Prisma.ScanOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ScanInclude<ExtArgs> | null
  where?: Prisma.ScanWhereInput
  orderBy?: Prisma.ScanOrderByWithRelationInput | Prisma.ScanOrderByWithRelationInput[]
  cursor?: Prisma.ScanWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ScanScalarFieldEnum | Prisma.ScanScalarFieldEnum[]
}

/**
 * OrganizationDepartment without action
 */
export type OrganizationDepartmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationDepartment
   */
  select?: Prisma.OrganizationDepartmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationDepartment
   */
  omit?: Prisma.OrganizationDepartmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationDepartmentInclude<ExtArgs> | null
}
