
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PersonalSubscription` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PersonalSubscription
 * 
 */
export type PersonalSubscriptionModel = runtime.Types.Result.DefaultSelection<Prisma.$PersonalSubscriptionPayload>

export type AggregatePersonalSubscription = {
  _count: PersonalSubscriptionCountAggregateOutputType | null
  _avg: PersonalSubscriptionAvgAggregateOutputType | null
  _sum: PersonalSubscriptionSumAggregateOutputType | null
  _min: PersonalSubscriptionMinAggregateOutputType | null
  _max: PersonalSubscriptionMaxAggregateOutputType | null
}

export type PersonalSubscriptionAvgAggregateOutputType = {
  scansPerMonth: number | null
  scansPerHour: number | null
  maxApiTokens: number | null
}

export type PersonalSubscriptionSumAggregateOutputType = {
  scansPerMonth: number | null
  scansPerHour: number | null
  maxApiTokens: number | null
}

export type PersonalSubscriptionMinAggregateOutputType = {
  id: string | null
  userId: string | null
  plan: string | null
  status: string | null
  stripeCustomerId: string | null
  stripeSubscriptionId: string | null
  stripePriceId: string | null
  currentPeriodStart: Date | null
  currentPeriodEnd: Date | null
  cancelAtPeriodEnd: boolean | null
  canceledAt: Date | null
  scansPerMonth: number | null
  scansPerHour: number | null
  maxApiTokens: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PersonalSubscriptionMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  plan: string | null
  status: string | null
  stripeCustomerId: string | null
  stripeSubscriptionId: string | null
  stripePriceId: string | null
  currentPeriodStart: Date | null
  currentPeriodEnd: Date | null
  cancelAtPeriodEnd: boolean | null
  canceledAt: Date | null
  scansPerMonth: number | null
  scansPerHour: number | null
  maxApiTokens: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PersonalSubscriptionCountAggregateOutputType = {
  id: number
  userId: number
  plan: number
  status: number
  stripeCustomerId: number
  stripeSubscriptionId: number
  stripePriceId: number
  currentPeriodStart: number
  currentPeriodEnd: number
  cancelAtPeriodEnd: number
  canceledAt: number
  scansPerMonth: number
  scansPerHour: number
  maxApiTokens: number
  features: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PersonalSubscriptionAvgAggregateInputType = {
  scansPerMonth?: true
  scansPerHour?: true
  maxApiTokens?: true
}

export type PersonalSubscriptionSumAggregateInputType = {
  scansPerMonth?: true
  scansPerHour?: true
  maxApiTokens?: true
}

export type PersonalSubscriptionMinAggregateInputType = {
  id?: true
  userId?: true
  plan?: true
  status?: true
  stripeCustomerId?: true
  stripeSubscriptionId?: true
  stripePriceId?: true
  currentPeriodStart?: true
  currentPeriodEnd?: true
  cancelAtPeriodEnd?: true
  canceledAt?: true
  scansPerMonth?: true
  scansPerHour?: true
  maxApiTokens?: true
  createdAt?: true
  updatedAt?: true
}

export type PersonalSubscriptionMaxAggregateInputType = {
  id?: true
  userId?: true
  plan?: true
  status?: true
  stripeCustomerId?: true
  stripeSubscriptionId?: true
  stripePriceId?: true
  currentPeriodStart?: true
  currentPeriodEnd?: true
  cancelAtPeriodEnd?: true
  canceledAt?: true
  scansPerMonth?: true
  scansPerHour?: true
  maxApiTokens?: true
  createdAt?: true
  updatedAt?: true
}

export type PersonalSubscriptionCountAggregateInputType = {
  id?: true
  userId?: true
  plan?: true
  status?: true
  stripeCustomerId?: true
  stripeSubscriptionId?: true
  stripePriceId?: true
  currentPeriodStart?: true
  currentPeriodEnd?: true
  cancelAtPeriodEnd?: true
  canceledAt?: true
  scansPerMonth?: true
  scansPerHour?: true
  maxApiTokens?: true
  features?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PersonalSubscriptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PersonalSubscription to aggregate.
   */
  where?: Prisma.PersonalSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSubscriptions to fetch.
   */
  orderBy?: Prisma.PersonalSubscriptionOrderByWithRelationInput | Prisma.PersonalSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PersonalSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PersonalSubscriptions
  **/
  _count?: true | PersonalSubscriptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PersonalSubscriptionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PersonalSubscriptionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PersonalSubscriptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PersonalSubscriptionMaxAggregateInputType
}

export type GetPersonalSubscriptionAggregateType<T extends PersonalSubscriptionAggregateArgs> = {
      [P in keyof T & keyof AggregatePersonalSubscription]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePersonalSubscription[P]>
    : Prisma.GetScalarType<T[P], AggregatePersonalSubscription[P]>
}




export type PersonalSubscriptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PersonalSubscriptionWhereInput
  orderBy?: Prisma.PersonalSubscriptionOrderByWithAggregationInput | Prisma.PersonalSubscriptionOrderByWithAggregationInput[]
  by: Prisma.PersonalSubscriptionScalarFieldEnum[] | Prisma.PersonalSubscriptionScalarFieldEnum
  having?: Prisma.PersonalSubscriptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PersonalSubscriptionCountAggregateInputType | true
  _avg?: PersonalSubscriptionAvgAggregateInputType
  _sum?: PersonalSubscriptionSumAggregateInputType
  _min?: PersonalSubscriptionMinAggregateInputType
  _max?: PersonalSubscriptionMaxAggregateInputType
}

export type PersonalSubscriptionGroupByOutputType = {
  id: string
  userId: string
  plan: string
  status: string
  stripeCustomerId: string | null
  stripeSubscriptionId: string | null
  stripePriceId: string | null
  currentPeriodStart: Date
  currentPeriodEnd: Date
  cancelAtPeriodEnd: boolean
  canceledAt: Date | null
  scansPerMonth: number
  scansPerHour: number
  maxApiTokens: number
  features: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: PersonalSubscriptionCountAggregateOutputType | null
  _avg: PersonalSubscriptionAvgAggregateOutputType | null
  _sum: PersonalSubscriptionSumAggregateOutputType | null
  _min: PersonalSubscriptionMinAggregateOutputType | null
  _max: PersonalSubscriptionMaxAggregateOutputType | null
}

export type GetPersonalSubscriptionGroupByPayload<T extends PersonalSubscriptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PersonalSubscriptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PersonalSubscriptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PersonalSubscriptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PersonalSubscriptionGroupByOutputType[P]>
      }
    >
  >



export type PersonalSubscriptionWhereInput = {
  AND?: Prisma.PersonalSubscriptionWhereInput | Prisma.PersonalSubscriptionWhereInput[]
  OR?: Prisma.PersonalSubscriptionWhereInput[]
  NOT?: Prisma.PersonalSubscriptionWhereInput | Prisma.PersonalSubscriptionWhereInput[]
  id?: Prisma.StringFilter<"PersonalSubscription"> | string
  userId?: Prisma.StringFilter<"PersonalSubscription"> | string
  plan?: Prisma.StringFilter<"PersonalSubscription"> | string
  status?: Prisma.StringFilter<"PersonalSubscription"> | string
  stripeCustomerId?: Prisma.StringNullableFilter<"PersonalSubscription"> | string | null
  stripeSubscriptionId?: Prisma.StringNullableFilter<"PersonalSubscription"> | string | null
  stripePriceId?: Prisma.StringNullableFilter<"PersonalSubscription"> | string | null
  currentPeriodStart?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  currentPeriodEnd?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFilter<"PersonalSubscription"> | boolean
  canceledAt?: Prisma.DateTimeNullableFilter<"PersonalSubscription"> | Date | string | null
  scansPerMonth?: Prisma.IntFilter<"PersonalSubscription"> | number
  scansPerHour?: Prisma.IntFilter<"PersonalSubscription"> | number
  maxApiTokens?: Prisma.IntFilter<"PersonalSubscription"> | number
  features?: Prisma.JsonNullableFilter<"PersonalSubscription">
  createdAt?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PersonalSubscriptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  status?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripePriceId?: Prisma.SortOrderInput | Prisma.SortOrder
  currentPeriodStart?: Prisma.SortOrder
  currentPeriodEnd?: Prisma.SortOrder
  cancelAtPeriodEnd?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrderInput | Prisma.SortOrder
  scansPerMonth?: Prisma.SortOrder
  scansPerHour?: Prisma.SortOrder
  maxApiTokens?: Prisma.SortOrder
  features?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type PersonalSubscriptionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  stripeCustomerId?: string
  stripeSubscriptionId?: string
  AND?: Prisma.PersonalSubscriptionWhereInput | Prisma.PersonalSubscriptionWhereInput[]
  OR?: Prisma.PersonalSubscriptionWhereInput[]
  NOT?: Prisma.PersonalSubscriptionWhereInput | Prisma.PersonalSubscriptionWhereInput[]
  plan?: Prisma.StringFilter<"PersonalSubscription"> | string
  status?: Prisma.StringFilter<"PersonalSubscription"> | string
  stripePriceId?: Prisma.StringNullableFilter<"PersonalSubscription"> | string | null
  currentPeriodStart?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  currentPeriodEnd?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFilter<"PersonalSubscription"> | boolean
  canceledAt?: Prisma.DateTimeNullableFilter<"PersonalSubscription"> | Date | string | null
  scansPerMonth?: Prisma.IntFilter<"PersonalSubscription"> | number
  scansPerHour?: Prisma.IntFilter<"PersonalSubscription"> | number
  maxApiTokens?: Prisma.IntFilter<"PersonalSubscription"> | number
  features?: Prisma.JsonNullableFilter<"PersonalSubscription">
  createdAt?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PersonalSubscription"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId" | "stripeCustomerId" | "stripeSubscriptionId">

export type PersonalSubscriptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  status?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrderInput | Prisma.SortOrder
  stripePriceId?: Prisma.SortOrderInput | Prisma.SortOrder
  currentPeriodStart?: Prisma.SortOrder
  currentPeriodEnd?: Prisma.SortOrder
  cancelAtPeriodEnd?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrderInput | Prisma.SortOrder
  scansPerMonth?: Prisma.SortOrder
  scansPerHour?: Prisma.SortOrder
  maxApiTokens?: Prisma.SortOrder
  features?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PersonalSubscriptionCountOrderByAggregateInput
  _avg?: Prisma.PersonalSubscriptionAvgOrderByAggregateInput
  _max?: Prisma.PersonalSubscriptionMaxOrderByAggregateInput
  _min?: Prisma.PersonalSubscriptionMinOrderByAggregateInput
  _sum?: Prisma.PersonalSubscriptionSumOrderByAggregateInput
}

export type PersonalSubscriptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PersonalSubscriptionScalarWhereWithAggregatesInput | Prisma.PersonalSubscriptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PersonalSubscriptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PersonalSubscriptionScalarWhereWithAggregatesInput | Prisma.PersonalSubscriptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PersonalSubscription"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PersonalSubscription"> | string
  plan?: Prisma.StringWithAggregatesFilter<"PersonalSubscription"> | string
  status?: Prisma.StringWithAggregatesFilter<"PersonalSubscription"> | string
  stripeCustomerId?: Prisma.StringNullableWithAggregatesFilter<"PersonalSubscription"> | string | null
  stripeSubscriptionId?: Prisma.StringNullableWithAggregatesFilter<"PersonalSubscription"> | string | null
  stripePriceId?: Prisma.StringNullableWithAggregatesFilter<"PersonalSubscription"> | string | null
  currentPeriodStart?: Prisma.DateTimeWithAggregatesFilter<"PersonalSubscription"> | Date | string
  currentPeriodEnd?: Prisma.DateTimeWithAggregatesFilter<"PersonalSubscription"> | Date | string
  cancelAtPeriodEnd?: Prisma.BoolWithAggregatesFilter<"PersonalSubscription"> | boolean
  canceledAt?: Prisma.DateTimeNullableWithAggregatesFilter<"PersonalSubscription"> | Date | string | null
  scansPerMonth?: Prisma.IntWithAggregatesFilter<"PersonalSubscription"> | number
  scansPerHour?: Prisma.IntWithAggregatesFilter<"PersonalSubscription"> | number
  maxApiTokens?: Prisma.IntWithAggregatesFilter<"PersonalSubscription"> | number
  features?: Prisma.JsonNullableWithAggregatesFilter<"PersonalSubscription">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PersonalSubscription"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PersonalSubscription"> | Date | string
}

export type PersonalSubscriptionCreateInput = {
  id?: string
  plan?: string
  status?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePriceId?: string | null
  currentPeriodStart?: Date | string
  currentPeriodEnd: Date | string
  cancelAtPeriodEnd?: boolean
  canceledAt?: Date | string | null
  scansPerMonth?: number
  scansPerHour?: number
  maxApiTokens?: number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPersonalSubscriptionInput
}

export type PersonalSubscriptionUncheckedCreateInput = {
  id?: string
  userId: string
  plan?: string
  status?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePriceId?: string | null
  currentPeriodStart?: Date | string
  currentPeriodEnd: Date | string
  cancelAtPeriodEnd?: boolean
  canceledAt?: Date | string | null
  scansPerMonth?: number
  scansPerHour?: number
  maxApiTokens?: number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonalSubscriptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePriceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentPeriodStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentPeriodEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFieldUpdateOperationsInput | boolean
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scansPerMonth?: Prisma.IntFieldUpdateOperationsInput | number
  scansPerHour?: Prisma.IntFieldUpdateOperationsInput | number
  maxApiTokens?: Prisma.IntFieldUpdateOperationsInput | number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPersonalSubscriptionNestedInput
}

export type PersonalSubscriptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePriceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentPeriodStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentPeriodEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFieldUpdateOperationsInput | boolean
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scansPerMonth?: Prisma.IntFieldUpdateOperationsInput | number
  scansPerHour?: Prisma.IntFieldUpdateOperationsInput | number
  maxApiTokens?: Prisma.IntFieldUpdateOperationsInput | number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonalSubscriptionCreateManyInput = {
  id?: string
  userId: string
  plan?: string
  status?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePriceId?: string | null
  currentPeriodStart?: Date | string
  currentPeriodEnd: Date | string
  cancelAtPeriodEnd?: boolean
  canceledAt?: Date | string | null
  scansPerMonth?: number
  scansPerHour?: number
  maxApiTokens?: number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonalSubscriptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePriceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentPeriodStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentPeriodEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFieldUpdateOperationsInput | boolean
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scansPerMonth?: Prisma.IntFieldUpdateOperationsInput | number
  scansPerHour?: Prisma.IntFieldUpdateOperationsInput | number
  maxApiTokens?: Prisma.IntFieldUpdateOperationsInput | number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonalSubscriptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePriceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentPeriodStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentPeriodEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFieldUpdateOperationsInput | boolean
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scansPerMonth?: Prisma.IntFieldUpdateOperationsInput | number
  scansPerHour?: Prisma.IntFieldUpdateOperationsInput | number
  maxApiTokens?: Prisma.IntFieldUpdateOperationsInput | number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonalSubscriptionNullableScalarRelationFilter = {
  is?: Prisma.PersonalSubscriptionWhereInput | null
  isNot?: Prisma.PersonalSubscriptionWhereInput | null
}

export type PersonalSubscriptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  status?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrder
  stripePriceId?: Prisma.SortOrder
  currentPeriodStart?: Prisma.SortOrder
  currentPeriodEnd?: Prisma.SortOrder
  cancelAtPeriodEnd?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrder
  scansPerMonth?: Prisma.SortOrder
  scansPerHour?: Prisma.SortOrder
  maxApiTokens?: Prisma.SortOrder
  features?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonalSubscriptionAvgOrderByAggregateInput = {
  scansPerMonth?: Prisma.SortOrder
  scansPerHour?: Prisma.SortOrder
  maxApiTokens?: Prisma.SortOrder
}

export type PersonalSubscriptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  status?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrder
  stripePriceId?: Prisma.SortOrder
  currentPeriodStart?: Prisma.SortOrder
  currentPeriodEnd?: Prisma.SortOrder
  cancelAtPeriodEnd?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrder
  scansPerMonth?: Prisma.SortOrder
  scansPerHour?: Prisma.SortOrder
  maxApiTokens?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonalSubscriptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  plan?: Prisma.SortOrder
  status?: Prisma.SortOrder
  stripeCustomerId?: Prisma.SortOrder
  stripeSubscriptionId?: Prisma.SortOrder
  stripePriceId?: Prisma.SortOrder
  currentPeriodStart?: Prisma.SortOrder
  currentPeriodEnd?: Prisma.SortOrder
  cancelAtPeriodEnd?: Prisma.SortOrder
  canceledAt?: Prisma.SortOrder
  scansPerMonth?: Prisma.SortOrder
  scansPerHour?: Prisma.SortOrder
  maxApiTokens?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PersonalSubscriptionSumOrderByAggregateInput = {
  scansPerMonth?: Prisma.SortOrder
  scansPerHour?: Prisma.SortOrder
  maxApiTokens?: Prisma.SortOrder
}

export type PersonalSubscriptionCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PersonalSubscriptionCreateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonalSubscriptionCreateOrConnectWithoutUserInput
  connect?: Prisma.PersonalSubscriptionWhereUniqueInput
}

export type PersonalSubscriptionUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PersonalSubscriptionCreateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonalSubscriptionCreateOrConnectWithoutUserInput
  connect?: Prisma.PersonalSubscriptionWhereUniqueInput
}

export type PersonalSubscriptionUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PersonalSubscriptionCreateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonalSubscriptionCreateOrConnectWithoutUserInput
  upsert?: Prisma.PersonalSubscriptionUpsertWithoutUserInput
  disconnect?: Prisma.PersonalSubscriptionWhereInput | boolean
  delete?: Prisma.PersonalSubscriptionWhereInput | boolean
  connect?: Prisma.PersonalSubscriptionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonalSubscriptionUpdateToOneWithWhereWithoutUserInput, Prisma.PersonalSubscriptionUpdateWithoutUserInput>, Prisma.PersonalSubscriptionUncheckedUpdateWithoutUserInput>
}

export type PersonalSubscriptionUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PersonalSubscriptionCreateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonalSubscriptionCreateOrConnectWithoutUserInput
  upsert?: Prisma.PersonalSubscriptionUpsertWithoutUserInput
  disconnect?: Prisma.PersonalSubscriptionWhereInput | boolean
  delete?: Prisma.PersonalSubscriptionWhereInput | boolean
  connect?: Prisma.PersonalSubscriptionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonalSubscriptionUpdateToOneWithWhereWithoutUserInput, Prisma.PersonalSubscriptionUpdateWithoutUserInput>, Prisma.PersonalSubscriptionUncheckedUpdateWithoutUserInput>
}

export type PersonalSubscriptionCreateWithoutUserInput = {
  id?: string
  plan?: string
  status?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePriceId?: string | null
  currentPeriodStart?: Date | string
  currentPeriodEnd: Date | string
  cancelAtPeriodEnd?: boolean
  canceledAt?: Date | string | null
  scansPerMonth?: number
  scansPerHour?: number
  maxApiTokens?: number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonalSubscriptionUncheckedCreateWithoutUserInput = {
  id?: string
  plan?: string
  status?: string
  stripeCustomerId?: string | null
  stripeSubscriptionId?: string | null
  stripePriceId?: string | null
  currentPeriodStart?: Date | string
  currentPeriodEnd: Date | string
  cancelAtPeriodEnd?: boolean
  canceledAt?: Date | string | null
  scansPerMonth?: number
  scansPerHour?: number
  maxApiTokens?: number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PersonalSubscriptionCreateOrConnectWithoutUserInput = {
  where: Prisma.PersonalSubscriptionWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonalSubscriptionCreateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedCreateWithoutUserInput>
}

export type PersonalSubscriptionUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.PersonalSubscriptionUpdateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PersonalSubscriptionCreateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedCreateWithoutUserInput>
  where?: Prisma.PersonalSubscriptionWhereInput
}

export type PersonalSubscriptionUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.PersonalSubscriptionWhereInput
  data: Prisma.XOR<Prisma.PersonalSubscriptionUpdateWithoutUserInput, Prisma.PersonalSubscriptionUncheckedUpdateWithoutUserInput>
}

export type PersonalSubscriptionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePriceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentPeriodStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentPeriodEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFieldUpdateOperationsInput | boolean
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scansPerMonth?: Prisma.IntFieldUpdateOperationsInput | number
  scansPerHour?: Prisma.IntFieldUpdateOperationsInput | number
  maxApiTokens?: Prisma.IntFieldUpdateOperationsInput | number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PersonalSubscriptionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  plan?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  stripeCustomerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeSubscriptionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePriceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  currentPeriodStart?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  currentPeriodEnd?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cancelAtPeriodEnd?: Prisma.BoolFieldUpdateOperationsInput | boolean
  canceledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  scansPerMonth?: Prisma.IntFieldUpdateOperationsInput | number
  scansPerHour?: Prisma.IntFieldUpdateOperationsInput | number
  maxApiTokens?: Prisma.IntFieldUpdateOperationsInput | number
  features?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PersonalSubscriptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  plan?: boolean
  status?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePriceId?: boolean
  currentPeriodStart?: boolean
  currentPeriodEnd?: boolean
  cancelAtPeriodEnd?: boolean
  canceledAt?: boolean
  scansPerMonth?: boolean
  scansPerHour?: boolean
  maxApiTokens?: boolean
  features?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["personalSubscription"]>

export type PersonalSubscriptionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  plan?: boolean
  status?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePriceId?: boolean
  currentPeriodStart?: boolean
  currentPeriodEnd?: boolean
  cancelAtPeriodEnd?: boolean
  canceledAt?: boolean
  scansPerMonth?: boolean
  scansPerHour?: boolean
  maxApiTokens?: boolean
  features?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["personalSubscription"]>

export type PersonalSubscriptionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  plan?: boolean
  status?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePriceId?: boolean
  currentPeriodStart?: boolean
  currentPeriodEnd?: boolean
  cancelAtPeriodEnd?: boolean
  canceledAt?: boolean
  scansPerMonth?: boolean
  scansPerHour?: boolean
  maxApiTokens?: boolean
  features?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["personalSubscription"]>

export type PersonalSubscriptionSelectScalar = {
  id?: boolean
  userId?: boolean
  plan?: boolean
  status?: boolean
  stripeCustomerId?: boolean
  stripeSubscriptionId?: boolean
  stripePriceId?: boolean
  currentPeriodStart?: boolean
  currentPeriodEnd?: boolean
  cancelAtPeriodEnd?: boolean
  canceledAt?: boolean
  scansPerMonth?: boolean
  scansPerHour?: boolean
  maxApiTokens?: boolean
  features?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PersonalSubscriptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "plan" | "status" | "stripeCustomerId" | "stripeSubscriptionId" | "stripePriceId" | "currentPeriodStart" | "currentPeriodEnd" | "cancelAtPeriodEnd" | "canceledAt" | "scansPerMonth" | "scansPerHour" | "maxApiTokens" | "features" | "createdAt" | "updatedAt", ExtArgs["result"]["personalSubscription"]>
export type PersonalSubscriptionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PersonalSubscriptionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PersonalSubscriptionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PersonalSubscriptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PersonalSubscription"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    plan: string
    status: string
    stripeCustomerId: string | null
    stripeSubscriptionId: string | null
    stripePriceId: string | null
    currentPeriodStart: Date
    currentPeriodEnd: Date
    cancelAtPeriodEnd: boolean
    canceledAt: Date | null
    scansPerMonth: number
    scansPerHour: number
    maxApiTokens: number
    features: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["personalSubscription"]>
  composites: {}
}

export type PersonalSubscriptionGetPayload<S extends boolean | null | undefined | PersonalSubscriptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload, S>

export type PersonalSubscriptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PersonalSubscriptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PersonalSubscriptionCountAggregateInputType | true
  }

export interface PersonalSubscriptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PersonalSubscription'], meta: { name: 'PersonalSubscription' } }
  /**
   * Find zero or one PersonalSubscription that matches the filter.
   * @param {PersonalSubscriptionFindUniqueArgs} args - Arguments to find a PersonalSubscription
   * @example
   * // Get one PersonalSubscription
   * const personalSubscription = await prisma.personalSubscription.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PersonalSubscriptionFindUniqueArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PersonalSubscription that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PersonalSubscriptionFindUniqueOrThrowArgs} args - Arguments to find a PersonalSubscription
   * @example
   * // Get one PersonalSubscription
   * const personalSubscription = await prisma.personalSubscription.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PersonalSubscriptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PersonalSubscription that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSubscriptionFindFirstArgs} args - Arguments to find a PersonalSubscription
   * @example
   * // Get one PersonalSubscription
   * const personalSubscription = await prisma.personalSubscription.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PersonalSubscriptionFindFirstArgs>(args?: Prisma.SelectSubset<T, PersonalSubscriptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PersonalSubscription that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSubscriptionFindFirstOrThrowArgs} args - Arguments to find a PersonalSubscription
   * @example
   * // Get one PersonalSubscription
   * const personalSubscription = await prisma.personalSubscription.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PersonalSubscriptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PersonalSubscriptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PersonalSubscriptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSubscriptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PersonalSubscriptions
   * const personalSubscriptions = await prisma.personalSubscription.findMany()
   * 
   * // Get first 10 PersonalSubscriptions
   * const personalSubscriptions = await prisma.personalSubscription.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const personalSubscriptionWithIdOnly = await prisma.personalSubscription.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PersonalSubscriptionFindManyArgs>(args?: Prisma.SelectSubset<T, PersonalSubscriptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PersonalSubscription.
   * @param {PersonalSubscriptionCreateArgs} args - Arguments to create a PersonalSubscription.
   * @example
   * // Create one PersonalSubscription
   * const PersonalSubscription = await prisma.personalSubscription.create({
   *   data: {
   *     // ... data to create a PersonalSubscription
   *   }
   * })
   * 
   */
  create<T extends PersonalSubscriptionCreateArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionCreateArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PersonalSubscriptions.
   * @param {PersonalSubscriptionCreateManyArgs} args - Arguments to create many PersonalSubscriptions.
   * @example
   * // Create many PersonalSubscriptions
   * const personalSubscription = await prisma.personalSubscription.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PersonalSubscriptionCreateManyArgs>(args?: Prisma.SelectSubset<T, PersonalSubscriptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PersonalSubscriptions and returns the data saved in the database.
   * @param {PersonalSubscriptionCreateManyAndReturnArgs} args - Arguments to create many PersonalSubscriptions.
   * @example
   * // Create many PersonalSubscriptions
   * const personalSubscription = await prisma.personalSubscription.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PersonalSubscriptions and only return the `id`
   * const personalSubscriptionWithIdOnly = await prisma.personalSubscription.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PersonalSubscriptionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PersonalSubscriptionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PersonalSubscription.
   * @param {PersonalSubscriptionDeleteArgs} args - Arguments to delete one PersonalSubscription.
   * @example
   * // Delete one PersonalSubscription
   * const PersonalSubscription = await prisma.personalSubscription.delete({
   *   where: {
   *     // ... filter to delete one PersonalSubscription
   *   }
   * })
   * 
   */
  delete<T extends PersonalSubscriptionDeleteArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionDeleteArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PersonalSubscription.
   * @param {PersonalSubscriptionUpdateArgs} args - Arguments to update one PersonalSubscription.
   * @example
   * // Update one PersonalSubscription
   * const personalSubscription = await prisma.personalSubscription.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PersonalSubscriptionUpdateArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionUpdateArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PersonalSubscriptions.
   * @param {PersonalSubscriptionDeleteManyArgs} args - Arguments to filter PersonalSubscriptions to delete.
   * @example
   * // Delete a few PersonalSubscriptions
   * const { count } = await prisma.personalSubscription.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PersonalSubscriptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PersonalSubscriptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PersonalSubscriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSubscriptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PersonalSubscriptions
   * const personalSubscription = await prisma.personalSubscription.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PersonalSubscriptionUpdateManyArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PersonalSubscriptions and returns the data updated in the database.
   * @param {PersonalSubscriptionUpdateManyAndReturnArgs} args - Arguments to update many PersonalSubscriptions.
   * @example
   * // Update many PersonalSubscriptions
   * const personalSubscription = await prisma.personalSubscription.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PersonalSubscriptions and only return the `id`
   * const personalSubscriptionWithIdOnly = await prisma.personalSubscription.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PersonalSubscriptionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PersonalSubscription.
   * @param {PersonalSubscriptionUpsertArgs} args - Arguments to update or create a PersonalSubscription.
   * @example
   * // Update or create a PersonalSubscription
   * const personalSubscription = await prisma.personalSubscription.upsert({
   *   create: {
   *     // ... data to create a PersonalSubscription
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PersonalSubscription we want to update
   *   }
   * })
   */
  upsert<T extends PersonalSubscriptionUpsertArgs>(args: Prisma.SelectSubset<T, PersonalSubscriptionUpsertArgs<ExtArgs>>): Prisma.Prisma__PersonalSubscriptionClient<runtime.Types.Result.GetResult<Prisma.$PersonalSubscriptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PersonalSubscriptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSubscriptionCountArgs} args - Arguments to filter PersonalSubscriptions to count.
   * @example
   * // Count the number of PersonalSubscriptions
   * const count = await prisma.personalSubscription.count({
   *   where: {
   *     // ... the filter for the PersonalSubscriptions we want to count
   *   }
   * })
  **/
  count<T extends PersonalSubscriptionCountArgs>(
    args?: Prisma.Subset<T, PersonalSubscriptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PersonalSubscriptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PersonalSubscription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSubscriptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PersonalSubscriptionAggregateArgs>(args: Prisma.Subset<T, PersonalSubscriptionAggregateArgs>): Prisma.PrismaPromise<GetPersonalSubscriptionAggregateType<T>>

  /**
   * Group by PersonalSubscription.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonalSubscriptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PersonalSubscriptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PersonalSubscriptionGroupByArgs['orderBy'] }
      : { orderBy?: PersonalSubscriptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PersonalSubscriptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPersonalSubscriptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PersonalSubscription model
 */
readonly fields: PersonalSubscriptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PersonalSubscription.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PersonalSubscriptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PersonalSubscription model
 */
export interface PersonalSubscriptionFieldRefs {
  readonly id: Prisma.FieldRef<"PersonalSubscription", 'String'>
  readonly userId: Prisma.FieldRef<"PersonalSubscription", 'String'>
  readonly plan: Prisma.FieldRef<"PersonalSubscription", 'String'>
  readonly status: Prisma.FieldRef<"PersonalSubscription", 'String'>
  readonly stripeCustomerId: Prisma.FieldRef<"PersonalSubscription", 'String'>
  readonly stripeSubscriptionId: Prisma.FieldRef<"PersonalSubscription", 'String'>
  readonly stripePriceId: Prisma.FieldRef<"PersonalSubscription", 'String'>
  readonly currentPeriodStart: Prisma.FieldRef<"PersonalSubscription", 'DateTime'>
  readonly currentPeriodEnd: Prisma.FieldRef<"PersonalSubscription", 'DateTime'>
  readonly cancelAtPeriodEnd: Prisma.FieldRef<"PersonalSubscription", 'Boolean'>
  readonly canceledAt: Prisma.FieldRef<"PersonalSubscription", 'DateTime'>
  readonly scansPerMonth: Prisma.FieldRef<"PersonalSubscription", 'Int'>
  readonly scansPerHour: Prisma.FieldRef<"PersonalSubscription", 'Int'>
  readonly maxApiTokens: Prisma.FieldRef<"PersonalSubscription", 'Int'>
  readonly features: Prisma.FieldRef<"PersonalSubscription", 'Json'>
  readonly createdAt: Prisma.FieldRef<"PersonalSubscription", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PersonalSubscription", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PersonalSubscription findUnique
 */
export type PersonalSubscriptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSubscription to fetch.
   */
  where: Prisma.PersonalSubscriptionWhereUniqueInput
}

/**
 * PersonalSubscription findUniqueOrThrow
 */
export type PersonalSubscriptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSubscription to fetch.
   */
  where: Prisma.PersonalSubscriptionWhereUniqueInput
}

/**
 * PersonalSubscription findFirst
 */
export type PersonalSubscriptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSubscription to fetch.
   */
  where?: Prisma.PersonalSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSubscriptions to fetch.
   */
  orderBy?: Prisma.PersonalSubscriptionOrderByWithRelationInput | Prisma.PersonalSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PersonalSubscriptions.
   */
  cursor?: Prisma.PersonalSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonalSubscriptions.
   */
  distinct?: Prisma.PersonalSubscriptionScalarFieldEnum | Prisma.PersonalSubscriptionScalarFieldEnum[]
}

/**
 * PersonalSubscription findFirstOrThrow
 */
export type PersonalSubscriptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSubscription to fetch.
   */
  where?: Prisma.PersonalSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSubscriptions to fetch.
   */
  orderBy?: Prisma.PersonalSubscriptionOrderByWithRelationInput | Prisma.PersonalSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PersonalSubscriptions.
   */
  cursor?: Prisma.PersonalSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonalSubscriptions.
   */
  distinct?: Prisma.PersonalSubscriptionScalarFieldEnum | Prisma.PersonalSubscriptionScalarFieldEnum[]
}

/**
 * PersonalSubscription findMany
 */
export type PersonalSubscriptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * Filter, which PersonalSubscriptions to fetch.
   */
  where?: Prisma.PersonalSubscriptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonalSubscriptions to fetch.
   */
  orderBy?: Prisma.PersonalSubscriptionOrderByWithRelationInput | Prisma.PersonalSubscriptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PersonalSubscriptions.
   */
  cursor?: Prisma.PersonalSubscriptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonalSubscriptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonalSubscriptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonalSubscriptions.
   */
  distinct?: Prisma.PersonalSubscriptionScalarFieldEnum | Prisma.PersonalSubscriptionScalarFieldEnum[]
}

/**
 * PersonalSubscription create
 */
export type PersonalSubscriptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * The data needed to create a PersonalSubscription.
   */
  data: Prisma.XOR<Prisma.PersonalSubscriptionCreateInput, Prisma.PersonalSubscriptionUncheckedCreateInput>
}

/**
 * PersonalSubscription createMany
 */
export type PersonalSubscriptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PersonalSubscriptions.
   */
  data: Prisma.PersonalSubscriptionCreateManyInput | Prisma.PersonalSubscriptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PersonalSubscription createManyAndReturn
 */
export type PersonalSubscriptionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * The data used to create many PersonalSubscriptions.
   */
  data: Prisma.PersonalSubscriptionCreateManyInput | Prisma.PersonalSubscriptionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PersonalSubscription update
 */
export type PersonalSubscriptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * The data needed to update a PersonalSubscription.
   */
  data: Prisma.XOR<Prisma.PersonalSubscriptionUpdateInput, Prisma.PersonalSubscriptionUncheckedUpdateInput>
  /**
   * Choose, which PersonalSubscription to update.
   */
  where: Prisma.PersonalSubscriptionWhereUniqueInput
}

/**
 * PersonalSubscription updateMany
 */
export type PersonalSubscriptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PersonalSubscriptions.
   */
  data: Prisma.XOR<Prisma.PersonalSubscriptionUpdateManyMutationInput, Prisma.PersonalSubscriptionUncheckedUpdateManyInput>
  /**
   * Filter which PersonalSubscriptions to update
   */
  where?: Prisma.PersonalSubscriptionWhereInput
  /**
   * Limit how many PersonalSubscriptions to update.
   */
  limit?: number
}

/**
 * PersonalSubscription updateManyAndReturn
 */
export type PersonalSubscriptionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * The data used to update PersonalSubscriptions.
   */
  data: Prisma.XOR<Prisma.PersonalSubscriptionUpdateManyMutationInput, Prisma.PersonalSubscriptionUncheckedUpdateManyInput>
  /**
   * Filter which PersonalSubscriptions to update
   */
  where?: Prisma.PersonalSubscriptionWhereInput
  /**
   * Limit how many PersonalSubscriptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PersonalSubscription upsert
 */
export type PersonalSubscriptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * The filter to search for the PersonalSubscription to update in case it exists.
   */
  where: Prisma.PersonalSubscriptionWhereUniqueInput
  /**
   * In case the PersonalSubscription found by the `where` argument doesn't exist, create a new PersonalSubscription with this data.
   */
  create: Prisma.XOR<Prisma.PersonalSubscriptionCreateInput, Prisma.PersonalSubscriptionUncheckedCreateInput>
  /**
   * In case the PersonalSubscription was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PersonalSubscriptionUpdateInput, Prisma.PersonalSubscriptionUncheckedUpdateInput>
}

/**
 * PersonalSubscription delete
 */
export type PersonalSubscriptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
  /**
   * Filter which PersonalSubscription to delete.
   */
  where: Prisma.PersonalSubscriptionWhereUniqueInput
}

/**
 * PersonalSubscription deleteMany
 */
export type PersonalSubscriptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PersonalSubscriptions to delete
   */
  where?: Prisma.PersonalSubscriptionWhereInput
  /**
   * Limit how many PersonalSubscriptions to delete.
   */
  limit?: number
}

/**
 * PersonalSubscription without action
 */
export type PersonalSubscriptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonalSubscription
   */
  select?: Prisma.PersonalSubscriptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonalSubscription
   */
  omit?: Prisma.PersonalSubscriptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonalSubscriptionInclude<ExtArgs> | null
}
