
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification',
  Organization: 'Organization',
  OrganizationMember: 'OrganizationMember',
  OrganizationDepartment: 'OrganizationDepartment',
  MemberRiskSnapshot: 'MemberRiskSnapshot',
  TrainingAssignment: 'TrainingAssignment',
  OrganizationInvite: 'OrganizationInvite',
  EmailDeliveryLog: 'EmailDeliveryLog',
  PersonalSubscription: 'PersonalSubscription',
  Subscription: 'Subscription',
  ApiToken: 'ApiToken',
  Scan: 'Scan',
  DashboardStats: 'DashboardStats',
  EmailScan: 'EmailScan',
  UserAction: 'UserAction',
  Department: 'Department'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VerificationScalarFieldEnum = (typeof VerificationScalarFieldEnum)[keyof typeof VerificationScalarFieldEnum]


export const OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameNormalized: 'nameNormalized',
  slug: 'slug',
  domain: 'domain',
  logo: 'logo',
  settings: 'settings',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  createdById: 'createdById'
} as const

export type OrganizationScalarFieldEnum = (typeof OrganizationScalarFieldEnum)[keyof typeof OrganizationScalarFieldEnum]


export const OrganizationMemberScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  departmentId: 'departmentId',
  role: 'role',
  joinedAt: 'joinedAt',
  updatedAt: 'updatedAt'
} as const

export type OrganizationMemberScalarFieldEnum = (typeof OrganizationMemberScalarFieldEnum)[keyof typeof OrganizationMemberScalarFieldEnum]


export const OrganizationDepartmentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  nameNormalized: 'nameNormalized',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrganizationDepartmentScalarFieldEnum = (typeof OrganizationDepartmentScalarFieldEnum)[keyof typeof OrganizationDepartmentScalarFieldEnum]


export const MemberRiskSnapshotScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  snapshotDate: 'snapshotDate',
  windowDays: 'windowDays',
  totalScans: 'totalScans',
  riskyScans: 'riskyScans',
  avgScore: 'avgScore',
  riskTier: 'riskTier',
  dominantAttackType: 'dominantAttackType',
  recommendation: 'recommendation',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MemberRiskSnapshotScalarFieldEnum = (typeof MemberRiskSnapshotScalarFieldEnum)[keyof typeof MemberRiskSnapshotScalarFieldEnum]


export const TrainingAssignmentScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  assignedById: 'assignedById',
  snapshotId: 'snapshotId',
  source: 'source',
  status: 'status',
  attackType: 'attackType',
  recommendation: 'recommendation',
  note: 'note',
  dueAt: 'dueAt',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TrainingAssignmentScalarFieldEnum = (typeof TrainingAssignmentScalarFieldEnum)[keyof typeof TrainingAssignmentScalarFieldEnum]


export const OrganizationInviteScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  email: 'email',
  role: 'role',
  token: 'token',
  invitedById: 'invitedById',
  status: 'status',
  sendAttempts: 'sendAttempts',
  lastSentAt: 'lastSentAt',
  lastError: 'lastError',
  acceptedAt: 'acceptedAt',
  canceledAt: 'canceledAt',
  consumedById: 'consumedById',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrganizationInviteScalarFieldEnum = (typeof OrganizationInviteScalarFieldEnum)[keyof typeof OrganizationInviteScalarFieldEnum]


export const EmailDeliveryLogScalarFieldEnum = {
  id: 'id',
  inviteId: 'inviteId',
  organizationId: 'organizationId',
  recipientEmail: 'recipientEmail',
  channel: 'channel',
  status: 'status',
  providerMessageId: 'providerMessageId',
  error: 'error',
  metadata: 'metadata',
  createdAt: 'createdAt'
} as const

export type EmailDeliveryLogScalarFieldEnum = (typeof EmailDeliveryLogScalarFieldEnum)[keyof typeof EmailDeliveryLogScalarFieldEnum]


export const PersonalSubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  plan: 'plan',
  status: 'status',
  stripeCustomerId: 'stripeCustomerId',
  stripeSubscriptionId: 'stripeSubscriptionId',
  stripePriceId: 'stripePriceId',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  canceledAt: 'canceledAt',
  scansPerMonth: 'scansPerMonth',
  scansPerHour: 'scansPerHour',
  maxApiTokens: 'maxApiTokens',
  features: 'features',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PersonalSubscriptionScalarFieldEnum = (typeof PersonalSubscriptionScalarFieldEnum)[keyof typeof PersonalSubscriptionScalarFieldEnum]


export const SubscriptionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  plan: 'plan',
  status: 'status',
  stripeCustomerId: 'stripeCustomerId',
  stripeSubscriptionId: 'stripeSubscriptionId',
  stripePriceId: 'stripePriceId',
  currentPeriodStart: 'currentPeriodStart',
  currentPeriodEnd: 'currentPeriodEnd',
  cancelAtPeriodEnd: 'cancelAtPeriodEnd',
  canceledAt: 'canceledAt',
  maxMembers: 'maxMembers',
  scansPerMonth: 'scansPerMonth',
  scansPerHourPerUser: 'scansPerHourPerUser',
  maxApiTokens: 'maxApiTokens',
  features: 'features',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SubscriptionScalarFieldEnum = (typeof SubscriptionScalarFieldEnum)[keyof typeof SubscriptionScalarFieldEnum]


export const ApiTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  name: 'name',
  organizationId: 'organizationId',
  userId: 'userId',
  createdById: 'createdById',
  expiresAt: 'expiresAt',
  lastUsedAt: 'lastUsedAt',
  requestCount: 'requestCount',
  hourlyLimit: 'hourlyLimit',
  isActive: 'isActive',
  lastResetAt: 'lastResetAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ApiTokenScalarFieldEnum = (typeof ApiTokenScalarFieldEnum)[keyof typeof ApiTokenScalarFieldEnum]


export const ScanScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  departmentId: 'departmentId',
  userId: 'userId',
  url: 'url',
  textContent: 'textContent',
  imageUrl: 'imageUrl',
  textScore: 'textScore',
  urlScore: 'urlScore',
  overallScore: 'overallScore',
  riskLevel: 'riskLevel',
  isPhishing: 'isPhishing',
  confidence: 'confidence',
  detectedThreats: 'detectedThreats',
  analysis: 'analysis',
  source: 'source',
  isDeleted: 'isDeleted',
  deletedAt: 'deletedAt',
  deletedBy: 'deletedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ScanScalarFieldEnum = (typeof ScanScalarFieldEnum)[keyof typeof ScanScalarFieldEnum]


export const DashboardStatsScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  totalScans: 'totalScans',
  threatsBlocked: 'threatsBlocked',
  safeSites: 'safeSites',
  scansThisWeek: 'scansThisWeek',
  scansThisMonth: 'scansThisMonth',
  lastScanAt: 'lastScanAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DashboardStatsScalarFieldEnum = (typeof DashboardStatsScalarFieldEnum)[keyof typeof DashboardStatsScalarFieldEnum]


export const EmailScanScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  departmentId: 'departmentId',
  emailSubject: 'emailSubject',
  emailSender: 'emailSender',
  detectedAt: 'detectedAt',
  isPhishing: 'isPhishing',
  detectedBy: 'detectedBy',
  links: 'links'
} as const

export type EmailScanScalarFieldEnum = (typeof EmailScanScalarFieldEnum)[keyof typeof EmailScanScalarFieldEnum]


export const UserActionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  departmentId: 'departmentId',
  emailScanId: 'emailScanId',
  actionType: 'actionType',
  link: 'link',
  actionAt: 'actionAt'
} as const

export type UserActionScalarFieldEnum = (typeof UserActionScalarFieldEnum)[keyof typeof UserActionScalarFieldEnum]


export const DepartmentScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type DepartmentScalarFieldEnum = (typeof DepartmentScalarFieldEnum)[keyof typeof DepartmentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

